import type { ServiceAdapter, AdapterContext, ProvisionResult } from "./types.js";
import { exec } from "../utils/exec.js";

/**
 * Stripe Payments Adapter
 * Sets up Stripe for payment processing
 */
export const stripePaymentsAdapter: ServiceAdapter = {
  name: "stripe/payments",
  description: "Stripe payment processing with products and price IDs",

  getRequiredTools(): string[] {
    return ["stripe"];
  },

  async check(context: AdapterContext): Promise<boolean> {
    try {
      // Check if Stripe API key exists in env
      if (context.existingEnv.STRIPE_SECRET_KEY && context.existingEnv.STRIPE_PUBLISHABLE_KEY) {
        return true;
      }

      // Check if stripe CLI is authenticated
      const { stdout } = await exec("stripe", ["config", "--list"], {
        timeout: 10_000,
      });

      return stdout.includes("test_mode_api_key") || stdout.includes("live_mode_api_key");
    } catch {
      return false;
    }
  },

  async provision(context: AdapterContext): Promise<ProvisionResult> {
    try {
      // Step 1: Ensure Stripe CLI is authenticated
      try {
        const { stdout: configOutput } = await exec("stripe", ["config", "--list"], {
          timeout: 10_000,
        });

        if (
          !configOutput.includes("test_mode_api_key") &&
          !configOutput.includes("live_mode_api_key")
        ) {
          return {
            success: false,
            error: "Stripe CLI not authenticated. Run: stripe login",
            message: "Please authenticate with Stripe CLI first",
          };
        }
      } catch {
        return {
          success: false,
          error: "Stripe CLI not installed or not authenticated",
          message: "Install Stripe CLI and run: stripe login",
        };
      }

      // Step 2: Get API keys
      const { stdout: apiKeysOutput } = await exec("stripe", ["config", "--list"], {
        timeout: 10_000,
      });

      const testKeyMatch = apiKeysOutput.match(/test_mode_api_key\s*=\s*(\S+)/);
      const publishableKeyMatch = apiKeysOutput.match(/test_mode_pub_key\s*=\s*(\S+)/);

      if (!testKeyMatch) {
        return {
          success: false,
          error: "Could not retrieve Stripe API keys",
          message: "Failed to get Stripe API keys from CLI config",
        };
      }

      const secretKey = testKeyMatch[1];

      // Step 3: Get publishable key from API
      let publishableKey = publishableKeyMatch?.[1];

      if (!publishableKey) {
        try {
          await exec("stripe", ["api", "/v1/accounts", "--method", "get"], {
            timeout: 10_000,
          });

          // Parse to get publishable key (would need proper JSON parsing in production)
          // For now, construct from secret key pattern
          publishableKey = secretKey.replace("sk_test_", "pk_test_");
        } catch {
          publishableKey = secretKey.replace("sk_test_", "pk_test_");
        }
      }

      // Step 4: Create a basic product (optional, can be skipped if products exist)
      const projectName = context.projectName || "default";

      try {
        const { stdout: productsOutput } = await exec(
          "stripe",
          ["products", "list", "--limit", "1"],
          {
            timeout: 10_000,
          },
        );

        // If no products, create a sample one
        if (!productsOutput.includes("prod_")) {
          await exec(
            "stripe",
            [
              "products",
              "create",
              "--name",
              `${projectName} Subscription`,
              "--description",
              "Auto-generated by kit",
            ],
            {
              timeout: 10_000,
            },
          );
        }
      } catch {
        // Product creation failed, but that's OK - keys are more important
      }

      return {
        success: true,
        message: "Stripe payments configured successfully",
        secrets: {
          STRIPE_SECRET_KEY: secretKey,
          STRIPE_PUBLISHABLE_KEY: publishableKey,
        },
        config: {
          service: "stripe/payments",
          mode: "test",
        },
      };
    } catch (error: unknown) {
      return {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
        message: "Failed to provision Stripe payments",
      };
    }
  },
};
