/**
 * kit memory learn — deterministically mine the store for RECURRING user
 * instructions worth promoting to a memory rule.
 *
 * Zero-LLM, local, no ML: kit *finds* the pattern by counting verbatim-normalized
 * user messages; *you* decide the rule (record it via `kit memory share` or your
 * rules file). Idea borrowed from headroom's `learn` (kit-research), done the kit
 * way — pure counting over the local store, no model call.
 *
 * The signal: a user who says the same thing 3+ times (across sessions, or over
 * and over in one) is telling you something that belongs in memory instead of
 * being re-typed. A message flagged `correction` (it reads like a redirection —
 * "no", "stop", "instead", "nej", "istället") is an even stronger candidate.
 */
import type { DatabaseSync } from "node:sqlite";

export interface LearnCandidate {
  /** Normalized instruction text — the grouping key. */
  normalized: string;
  /** A representative original message (first seen, trimmed). */
  example: string;
  /** Total occurrences across the store. */
  count: number;
  /** Distinct sessions it appeared in — the cross-session recurrence signal. */
  sessions: number;
  /** True if it reads like a correction/redirection (bilingual sv/en). */
  correction: boolean;
}

export interface LearnOptions {
  /** Min total occurrences for a candidate (default 3). */
  minCount?: number;
  /** Min distinct sessions (default 1 — off; raise to require cross-session). */
  minSessions?: number;
  /** Max candidates returned (default 20). */
  limit?: number;
}

// Correction / redirection signals — bilingual (this user works in sv + en).
// Word-boundary anchored so "not" doesn't fire inside "notation".
const CORRECTION_RE =
  /\b(no|nope|don'?t|stop|actually|wrong|instead|not that|nej|sluta|fel|inte|istället|igen)\b/i;

/**
 * Harness scaffolding lands in the store as `type='user'` rows but is NOT something
 * the user typed — injected reminders, slash-command echoes, session-continuation
 * banners, hook output. It recurs every session, so without filtering it dominates
 * `learn`'s ranking and buries the real instructions (found by dogfooding: the top
 * "recurring instructions" were `<system-reminder>`, `/model`, and "Continue from
 * where you left off"). Match STRUCTURAL markers (harness tags, a leading slash
 * command) and a few verbatim harness phrases only — never generic words — so a
 * genuine instruction is never dropped.
 */
const BOILERPLATE_TAG_RE =
  /<\/?(?:system-reminder|local-command-caveat|local-command-stdout|local-command-stderr|command-name|command-message|command-args|untrusted_external_data|github-webhook-activity|task-notification|user-prompt-submit-hook|session-start-hook|bash-input|bash-stdout|bash-stderr)\b/i;

// A message that is *just* a slash-command echo ("/model sonnet", "/clear",
// "/loop 5m /foo"). Anchored to the start so a sentence mentioning a path like
// "/etc/hosts is wrong" is not misread as a command (that still reads as an
// instruction). A lone "/" or "/ something" (space after slash) is not a command.
const SLASH_COMMAND_RE = /^\/[a-z][\w-]*(?:\s|$)/i;

// Claude Code hook output that is stored as a user message: "Stop hook feedback: …",
// "UserPromptSubmit hook success: …", "SessionStart:resume hook success: …", etc.
const HOOK_OUTPUT_RE = /\bhook (?:success|feedback|error|blocked):/i;

// Image placeholder / coordinate note the harness injects for pasted images, e.g.
// "[Image: original 2560x2000 … Multiply coordinates by 1.28 …]" or "[Image #1]".
const IMAGE_NOTE_RE = /^\[image\b/i;

// Verbatim harness phrases (substring, case-insensitive), each specific enough that
// it cannot plausibly be a user instruction.
const BOILERPLATE_PHRASES = [
  "continue from where you left off",
  "this session is being continued from a previous conversation",
  "the messages below were generated by the user while running local commands",
  "the indented items below are stored data",
  "before answering anything project-specific, run",
  "request interrupted by user",
];

/** True when a stored `user` message is harness scaffolding, not a real instruction. */
export function isBoilerplate(raw: string): boolean {
  const s = raw.trim();
  if (!s) return true;
  if (
    BOILERPLATE_TAG_RE.test(s) ||
    SLASH_COMMAND_RE.test(s) ||
    HOOK_OUTPUT_RE.test(s) ||
    IMAGE_NOTE_RE.test(s)
  ) {
    return true;
  }
  const lower = s.toLowerCase();
  return BOILERPLATE_PHRASES.some((p) => lower.includes(p));
}

/**
 * Normalize a user message to a grouping key: lowercase, strip markdown/punctuation,
 * collapse whitespace. Two messages that differ only in casing or punctuation group
 * together; substantively different messages do not.
 */
export function normalizeInstruction(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/[`*_>#[\](){}"'.,!?;:/\\-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Rank recurring user instructions. Groups user messages by their normalized text,
 * keeps those seen `minCount`+ times (and in `minSessions`+ distinct sessions), and
 * ranks by distinct sessions, then raw count, then correction-first. Harness
 * scaffolding (see `isBoilerplate`), very short (< 3 words: "ok", "kör", "yes") and
 * very long (> 50 words: one-off context dumps) messages are skipped — none is a
 * repeatable user instruction.
 */
export function learnRecurring(db: DatabaseSync, opts: LearnOptions = {}): LearnCandidate[] {
  const minCount = opts.minCount ?? 3;
  const minSessions = opts.minSessions ?? 1;
  const limit = opts.limit ?? 20;

  const rows = db
    .prepare(
      `SELECT content, session_id FROM messages
       WHERE type = 'user' AND content IS NOT NULL AND content != ''`,
    )
    .all() as { content: string; session_id: string }[];

  const groups = new Map<string, { example: string; count: number; sessions: Set<string> }>();
  for (const r of rows) {
    if (isBoilerplate(r.content)) continue; // harness scaffolding, not a user instruction
    const normalized = normalizeInstruction(r.content);
    const words = normalized.split(" ").filter(Boolean);
    if (words.length < 3 || words.length > 50) continue;
    let g = groups.get(normalized);
    if (!g) {
      g = { example: r.content.replace(/\s+/g, " ").trim(), count: 0, sessions: new Set() };
      groups.set(normalized, g);
    }
    g.count++;
    g.sessions.add(r.session_id);
  }

  const candidates: LearnCandidate[] = [];
  for (const [normalized, g] of groups) {
    if (g.count < minCount || g.sessions.size < minSessions) continue;
    candidates.push({
      normalized,
      example: g.example.slice(0, 200),
      count: g.count,
      sessions: g.sessions.size,
      correction: CORRECTION_RE.test(normalized),
    });
  }
  candidates.sort(
    (a, b) =>
      b.sessions - a.sessions || b.count - a.count || Number(b.correction) - Number(a.correction),
  );
  return candidates.slice(0, limit);
}
