#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)
VERIFICATION_PENDING=0

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  if (( VERIFICATION_PENDING )); then
    printf '\n%s%s  ⚠ Setup configured; end-to-end verification incomplete%s\n' "$BOLD" "$YELLOW" "$RESET"
  else
    printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  fi
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

if [[ ! -t 0 ]]; then
  printf 'This wizard needs an interactive terminal (TTY). Run: kit mcp web\n' >&2
  exit 1
fi

banner "kit → ChatGPT web"

stage "Prerequisites"
say "ChatGPT reaches kits private stdio MCP through OpenAI Secure MCP Tunnel."
KIT_BIN=$(command -v kit || true)
if [[ -z "$KIT_BIN" ]]; then
  warn "kit is not on PATH. Install it, then re-run this wizard."
  exit 1
fi
if ! command -v tunnel-client >/dev/null 2>&1; then
  open_url "https://developers.openai.com/api/docs/guides/secure-mcp-tunnels"
  warn "tunnel-client is missing. Install the current binary from OpenAI Platform, then re-run."
  exit 1
fi
step "kit: $KIT_BIN"
step "tunnel-client: $(command -v tunnel-client)"
pause "Both commands found. Press Enter to continue."

stage "Create the tunnel"
open_url "https://platform.openai.com/settings/organization/tunnels"
step "Create a tunnel for this machine or select an existing one."
step "Associate both the Platform organization and the ChatGPT workspace that will use it."
step "Grant your operator Tunnels Read + Use; tunnel creation also needs Manage."
ask TUNNEL_ID "Paste the tunnel ID (starts tunnel_):"
if [[ ! "$TUNNEL_ID" =~ ^tunnel_[A-Za-z0-9_-]{16,}$ ]]; then
  warn "Unexpected tunnel ID. Copy the full tunnel_… value from Platform settings."
  exit 1
fi

stage "Runtime credential"
say "Create or copy the tunnel runtime API key from Platform tunnel settings."
say "Store it in your normal vault as CONTROL_PLANE_API_KEY for future restarts."
ask_secret CONTROL_PLANE_API_KEY "Paste runtime API key (hidden; used only by this process):"
if [[ -z "$CONTROL_PLANE_API_KEY" ]]; then
  warn "Runtime API key is required. Nothing was changed."
  exit 1
fi

stage "Initialize local stdio profile"
say "tunnel-client will launch the exact kit binary shown in stage 1 with the mcp subcommand."
printf '  %sProfile name [kit-local-stdio]:%s ' "$BOLD" "$RESET"
read -r TUNNEL_PROFILE || true
TUNNEL_PROFILE=${TUNNEL_PROFILE:-kit-local-stdio}
if [[ ! "$TUNNEL_PROFILE" =~ ^[A-Za-z0-9._-]+$ ]]; then
  warn "Profile may contain only letters, digits, dot, underscore and dash."
  exit 1
fi
if ! confirm "Write or update tunnel-client profile '$TUNNEL_PROFILE'?"; then
  warn "Stopped before profile creation."
  exit 1
fi
export CONTROL_PLANE_API_KEY
tunnel-client init \
  --sample sample_mcp_stdio_local \
  --profile "$TUNNEL_PROFILE" \
  --tunnel-id "$TUNNEL_ID" \
  --mcp-command "$KIT_BIN mcp"

stage "Verify and start"
step "Running tunnel-client doctor before exposing any tool."
tunnel-client doctor --profile "$TUNNEL_PROFILE" --explain
KIT_TUNNEL_RUN_DIR="${KIT_TUNNEL_RUN_DIR:-$HOME/.kit/tunnels}"
mkdir -p "$KIT_TUNNEL_RUN_DIR"
chmod 700 "$KIT_TUNNEL_RUN_DIR"
TUNNEL_LOG="$KIT_TUNNEL_RUN_DIR/$TUNNEL_PROFILE.log"
TUNNEL_PID_FILE="$KIT_TUNNEL_RUN_DIR/$TUNNEL_PROFILE.pid"
if [[ -f "$TUNNEL_PID_FILE" ]] && kill -0 "$(cat "$TUNNEL_PID_FILE")" 2>/dev/null; then
  note "tunnel-client already runs as PID $(cat "$TUNNEL_PID_FILE")"
else
  nohup tunnel-client run --profile "$TUNNEL_PROFILE" >"$TUNNEL_LOG" 2>&1 &
  TUNNEL_PID=$!
  printf '%s\n' "$TUNNEL_PID" > "$TUNNEL_PID_FILE"
  chmod 600 "$TUNNEL_LOG" "$TUNNEL_PID_FILE"
  sleep 2
  if ! kill -0 "$TUNNEL_PID" 2>/dev/null; then
    warn "tunnel-client stopped during startup. Inspect: $TUNNEL_LOG"
    exit 1
  fi
  note "tunnel-client running as PID $TUNNEL_PID; log: $TUNNEL_LOG"
fi

stage "Connect ChatGPT"
open_url "https://chatgpt.com/plugins"
step "If needed: Settings → Security and login → enable Developer mode."
step "Select + → create developer-mode app → Connection: Tunnel."
step "Choose this tunnel (or paste $TUNNEL_ID), create the app, then review discovered kit tools."
step "Call kit_memory with a harmless search to verify the complete web path."
if ! confirm "Did ChatGPT successfully call a kit tool?"; then
  VERIFICATION_PENDING=1
  SKIPPED+=("End-to-end ChatGPT tool call remains UNVERIFIED; re-run and confirm only after a real kit_memory call succeeds")
fi

CONTROL_PLANE_API_KEY=""
unset CONTROL_PLANE_API_KEY
SKIPPED+=("After a reboot, load CONTROL_PLANE_API_KEY from your vault and run: tunnel-client run --profile $TUNNEL_PROFILE")
finish
exit "$VERIFICATION_PENDING"
