#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — npm trusted publishing (OIDC) for every package this repo ships.
#
# Why this exists: npm is retiring 2FA-bypass granular access tokens as a
# publishing credential (phase 2, ~January 2027, leaves them able to read
# private packages and STAGE a publish for human 2FA approval — not to publish).
# The migration target is trusted publishing: GitHub Actions exchanges its OIDC
# identity for a short-lived credential, so no long-lived npm secret exists.
#
# The client-side prerequisite already shipped in 6.6.4 (publish.yml installs
# npm@^11.5.1; trusted publishing needs npm >= 11.5.1 on node >= 22.14.0). What
# remains is registry-side and can only be done in a browser, one package at a
# time, because npm allows exactly ONE trusted publisher per package and the npm
# CLI has no command that reads or writes the setting (checked on npm 11.19.0:
# `npm access` covers status/collaborators/grant/revoke and nothing else).
#
# So this wizard cannot verify the configuration for you. It verifies everything
# it CAN — the workflow file, the environment name, the real package list from
# this repo — records what you confirm in a state file so you can stop and
# resume, and ends by removing the token from the workflow and pointing you at a
# prerelease as the only honest test.
# ──────────────────────────────────────────────────────────────────────────

STATE_FILE="${STATE_FILE:-.kit/trusted-publishing.state}"
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

# The packages this repo actually publishes: the root plus every non-private
# workspace. Derived, never hardcoded — a list typed into a wizard drifts from
# the repo the moment someone adds a plugin, and a MISSED package is exactly the
# failure this migration must not have (no token + no trusted publisher = that
# package's publish step fails).
# NOTE: read-loop, not `mapfile` — macOS ships bash 3.2, where mapfile does not
# exist. This script must run on the machine that publishes, and that machine is
# a Mac.
PACKAGES=()
while IFS= read -r _pkg_name; do
  [[ -n "$_pkg_name" ]] && PACKAGES+=("$_pkg_name")
done < <(node -e '
  const fs = require("fs"), path = require("path");
  const names = [JSON.parse(fs.readFileSync("package.json", "utf8")).name];
  for (const dir of fs.readdirSync("packages", { withFileTypes: true })) {
    if (!dir.isDirectory()) continue;
    const file = path.join("packages", dir.name, "package.json");
    if (!fs.existsSync(file)) continue;
    const pkg = JSON.parse(fs.readFileSync(file, "utf8"));
    if (pkg.private) continue;
    names.push(pkg.name);
  }
  console.log(names.join("\n"));
')

if (( ${#PACKAGES[@]} == 0 )); then
  printf 'could not read the package list from this repo — run from the kit repo root\n' >&2
  exit 1
fi

WORKFLOW_FILE="publish.yml"
ENVIRONMENT="npm-publish"
ORIGIN_URL="$(git remote get-url origin 2>/dev/null || echo "")"
# github.com/OWNER/REPO(.git) and git@github.com:OWNER/REPO(.git) → OWNER, REPO.
# Derived so a fork configures itself, not the upstream it was cloned from. Done
# with parameter expansion rather than a regex: POSIX ERE (which macOS sed
# speaks) has no lazy quantifier, so the obvious `([^/]+?)(\.git)?$` is a syntax
# error there — measured, not assumed.
_origin="${ORIGIN_URL%.git}"
_origin="${_origin%/}"
GH_REPO="${_origin##*/}"
_origin_owner="${_origin%/*}"
GH_OWNER="${_origin_owner##*[:/]}"

# state_done PKG — has this package already been confirmed in an earlier run?
state_done() {
  [[ -f "$STATE_FILE" ]] && grep -qxF "done $1" "$STATE_FILE"
}

# state_record PKG — remember a confirmed package so a re-run skips it.
state_record() {
  mkdir -p "$(dirname "$STATE_FILE")"
  state_done "$1" || printf 'done %s\n' "$1" >> "$STATE_FILE"
}

TOTAL_STAGES=$(( ${#PACKAGES[@]} + 5 ))

banner "npm trusted publishing — ${#PACKAGES[@]} packages"

# ── Stage 1: preflight ────────────────────────────────────────────────────
stage "Preflight — what this wizard checked"
if [[ ! -f ".github/workflows/$WORKFLOW_FILE" ]]; then
  warn "no .github/workflows/$WORKFLOW_FILE — run this from the kit repo root"
  exit 1
fi
say "workflow file    .github/workflows/$WORKFLOW_FILE  ✓ exists"
say "repository       $GH_OWNER/$GH_REPO  (from origin)"

if grep -qE 'npm (i|install) -g npm@\^?11\.[5-9]|npm@\^?1[2-9]' ".github/workflows/$WORKFLOW_FILE"; then
  say "npm client       >= 11.5.1 installed by the job  ✓ (trusted publishing needs it)"
else
  warn "publish.yml does not install npm >= 11.5.1 — trusted publishing needs it; fix that first"
  exit 1
fi

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if gh api "repos/$GH_OWNER/$GH_REPO/environments" --jq '.environments[].name' 2>/dev/null \
    | grep -qxF "$ENVIRONMENT"; then
    say "environment      $ENVIRONMENT  ✓ exists on the repo"
  else
    warn "environment '$ENVIRONMENT' not found on $GH_OWNER/$GH_REPO"
    say "Leave the Environment field EMPTY in npm's form, or create the environment first."
    SKIPPED+=("create the '$ENVIRONMENT' environment, then re-run and fill it in npm's form")
  fi
else
  SKIPPED+=("verify the '$ENVIRONMENT' environment exists (gh missing or unauthenticated)")
  warn "gh unavailable — could not confirm the environment exists"
fi

printf '\n'
say "Packages to configure (${#PACKAGES[@]}), derived from this repo:"
for pkg in "${PACKAGES[@]}"; do
  if state_done "$pkg"; then note "  ✓ $pkg  (already recorded)"; else note "  · $pkg"; fi
done
printf '\n'
note "progress is recorded in $STATE_FILE — Ctrl-C any time and re-run"
pause "Press Enter to continue"

# ── Stage 2: be the right npm user ────────────────────────────────────────
stage "npmjs.com — sign in as an owner"
say "Every field after this is typed into npm's web UI; the CLI has no command"
say "for it. You need to be signed in as a package OWNER (maintainer is not"
say "enough to change publishing settings)."
open_url "https://www.npmjs.com/login"
step "Sign in, completing 2FA if prompted."
pause "Signed in? Press Enter"

# ── One stage per package ─────────────────────────────────────────────────
# Identical instructions each time, so muscle memory takes over after the first
# two: same owner, same repo, same workflow filename, same environment.
for pkg in "${PACKAGES[@]}"; do
  stage "$pkg"
  if state_done "$pkg"; then
    say "Already recorded as configured in an earlier run — skipping."
    note "To redo it, remove the line 'done $pkg' from $STATE_FILE"
    pause "Press Enter for the next package"
    continue
  fi

  open_url "https://www.npmjs.com/package/$pkg/access"
  step "On that Settings page, find the 'Trusted Publisher' section."
  step "Under 'Select your publisher', click GitHub Actions."
  printf '\n'
  say "Fill it in EXACTLY:"
  note "  Organization or user   $GH_OWNER"
  note "  Repository             $GH_REPO"
  note "  Workflow filename      $WORKFLOW_FILE      (filename only — no path)"
  note "  Environment name       $ENVIRONMENT"
  printf '\n'
  say "Naming the environment is the part worth not skipping: it means only the"
  say "reviewer-gated job can mint a credential. Without it, any run of that"
  say "workflow on any ref can publish."
  step "Save."
  printf '\n'
  if confirm "Saved the trusted publisher for $pkg"; then
    state_record "$pkg"
    say "recorded ✓"
  else
    warn "not recorded — re-run the wizard to pick $pkg up again"
    SKIPPED+=("configure the trusted publisher for $pkg")
  fi
  pause "Press Enter for the next package"
done

# ── Stage N-2: restrict token access (optional, recommended) ──────────────
stage "Optional — stop tokens from publishing at all"
say "A trusted publisher does not by itself forbid a token from publishing. npm"
say "recommends restricting that per package once OIDC works, which is what turns"
say "'we also have OIDC' into 'only OIDC can publish'."
printf '\n'
say "Do this AFTER a successful OIDC release (the last stage), not before — it is"
say "the setting that removes your fallback."
note "Per package: Settings → Publishing access → require two-factor or trusted"
note "publisher, i.e. disallow plain tokens."
printf '\n'
SKIPPED+=("after the first OIDC release: restrict token publishing per package (${#PACKAGES[@]} packages)")
pause "Understood? Press Enter"

# ── Stage N-1: take the token out of the workflow ─────────────────────────
stage "publish.yml — remove the npm token"
missing=()
for pkg in "${PACKAGES[@]}"; do
  state_done "$pkg" || missing+=("$pkg")
done
if (( ${#missing[@]} )); then
  warn "${#missing[@]} package(s) not yet confirmed: ${missing[*]}"
  say "Removing the token now would break exactly those packages' publish steps:"
  say "no token AND no trusted publisher means that step fails. Re-run the wizard"
  say "when they are done — nothing else here is lost."
  SKIPPED+=("remove NODE_AUTH_TOKEN from publish.yml (blocked: ${#missing[@]} package(s) unconfigured)")
else
  say "All ${#PACKAGES[@]} packages recorded. The token can come out."
  note "npm uses NODE_AUTH_TOKEN when it is present, so OIDC only takes over once"
  note "that env is gone — the two cannot both be in effect."
  printf '\n'
  say "--provenance is deliberately KEPT: provenance is automatic under trusted"
  say "publishing, so the flag is a no-op there, and leaving it in states the"
  say "intent. If the first OIDC publish rejects the flag, drop it then."
  printf '\n'
  if confirm "Edit .github/workflows/$WORKFLOW_FILE on a new branch now"; then
    branch="chore/trusted-publishing-drop-npm-token"
    git checkout -b "$branch" 2>/dev/null || git checkout "$branch"
    # Fail-closed: refuse a partial edit. An `env:` whose only child was the token
    # must lose the `env:` key too, or the YAML is invalid.
    if node -e '
      const fs = require("fs");
      const file = ".github/workflows/" + process.argv[1];
      const src = fs.readFileSync(file, "utf8");
      const lines = src.split("\n");
      const out = [];
      let removed = 0;
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (/^\s*NODE_AUTH_TOKEN:\s*\$\{\{\s*secrets\.NPM_TOKEN\s*\}\}\s*$/.test(line)) {
          removed++;
          // Drop the parent `env:` when this was its only entry.
          const prev = out[out.length - 1] ?? "";
          const next = lines[i + 1] ?? "";
          const indent = (s) => s.match(/^\s*/)[0].length;
          if (/^\s*env:\s*$/.test(prev) && indent(next) <= indent(prev)) out.pop();
          continue;
        }
        out.push(line);
      }
      if (removed === 0) { console.error("no NODE_AUTH_TOKEN lines found — nothing to do"); process.exit(2); }
      const result = out.join("\n");
      // Fail closed on a token reference that still EXECUTES. Comments are checked
      // separately: this workflow explains the token in prose, and refusing on prose
      // would make the edit impossible, while silently leaving prose that describes a
      // credential the job no longer uses is how docs start lying. Same distinction the
      // R1-fail-open-ci helper had to learn — a comment is not code, and not nothing.
      const live = result.split("\n").filter((l) => !/^\s*#/.test(l));
      if (live.some((l) => /NPM_TOKEN/.test(l))) {
        console.error("NPM_TOKEN still referenced in an executing line — refusing");
        process.exit(3);
      }
      fs.writeFileSync(file, result);
      console.log("removed " + removed + " NODE_AUTH_TOKEN line(s)");
      const prose = result
        .split("\n")
        .map((l, i) => [i + 1, l])
        .filter(([, l]) => /^\s*#/.test(l) && /NPM_TOKEN/.test(l));
      if (prose.length) {
        console.log("");
        console.log(prose.length + " comment line(s) still describe the token — update the prose in the same PR:");
        for (const [n, l] of prose) console.log("  " + file + ":" + n + " " + l.trim());
      }
    ' "$WORKFLOW_FILE"; then
      git --no-pager diff --stat
      say "Review with: git --no-pager diff"
      note "Then commit, open a PR, and let CI run before merging."
    else
      warn "the edit was refused — publish.yml is unchanged; do it by hand"
      SKIPPED+=("remove NODE_AUTH_TOKEN from publish.yml by hand")
    fi
  else
    SKIPPED+=("remove NODE_AUTH_TOKEN from publish.yml when ready")
  fi
fi
pause "Press Enter"

# ── Stage N: prove it with a prerelease ───────────────────────────────────
stage "Prove it — a prerelease, not the next real version"
say "Nothing so far has been verified by anything but your own confirmation. The"
say "only honest test is a publish, and a PRERELEASE is the one that cannot hurt:"
say "publish.yml routes any version containing a hyphen to the 'next' dist-tag, so"
say "'latest' does not move."
printf '\n'
say "The sequence (each of these is already gated in the job):"
note "  1. bump package.json to e.g. 6.6.5-rc.1 on a branch"
note "  2. add a '## [6.6.5-rc.1]' CHANGELOG section — the job REFUSES to publish"
note "     a version the changelog does not document, before it publishes"
note "  3. merge, then tag the release commit SIGNED and push it:"
note "       git tag -s v6.6.5-rc.1 <commit> -m 'v6.6.5-rc.1 — OIDC smoke test'"
note "       git push origin v6.6.5-rc.1"
note "  4. approve the '$ENVIRONMENT' environment when GitHub asks"
printf '\n'
say "Then verify — expect 'next' to move and 'latest' to stay put:"
note "  npm view $(printf '%s' "${PACKAGES[0]}") dist-tags"
note "  npm view $(printf '%s' "${PACKAGES[0]}")@6.6.5-rc.1 --json | jq .dist.attestations"
printf '\n'
warn "If a package's publish step fails with a 404/403, its trusted publisher is"
warn "missing or its fields do not match. The workspace loop is idempotent — fix"
warn "that one package and re-run the job; already-published packages are skipped."
pause "Press Enter to finish"

finish
