import { afterEach, it } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createServer } from "node:http";
import {
  mkdtempSync,
  mkdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { execFile } from "node:child_process";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceMode = import.meta.url.endsWith(".ts");
const cli = join(root, sourceMode ? "src" : "dist", sourceMode ? "cli.ts" : "cli.js");
const cliArgs = sourceMode ? ["--import", import.meta.resolve("tsx"), cli] : [cli];
const dirs: string[] = [];

afterEach(() => {
  while (dirs.length) rmSync(dirs.pop()!, { recursive: true, force: true });
});

async function runCli(
  cwd: string,
  args: string[],
  env: NodeJS.ProcessEnv = {},
): Promise<{ code: number; output: string }> {
  return new Promise((done) => {
    execFile(
      process.execPath,
      [...cliArgs, ...args],
      {
        cwd,
        env: {
          ...process.env,
          HOME: join(cwd, "home"),
          USERPROFILE: join(cwd, "home"),
          NO_COLOR: "1",
          ...env,
        },
        timeout: 15_000,
      },
      (error, stdout, stderr) => {
        done({
          code: error ? (typeof error.code === "number" ? error.code : -1) : 0,
          output: stdout + stderr + (error && typeof error.code !== "number" ? String(error) : ""),
        });
      },
    );
  });
}

it("CLI refuses symlinked hooks without partially installing or removing gates", async () => {
  const cwd = mkdtempSync(join(tmpdir(), "kit-hook-cli-symlink-"));
  dirs.push(cwd);
  execFileSync("git", ["init", "-q", cwd]);
  mkdirSync(join(cwd, "home"));
  writeFileSync(
    join(cwd, ".kit.toml"),
    '[hooks]\npre-commit = ["npm test"]\npre-push = ["npm audit"]\n',
  );
  const hooks = join(cwd, ".git", "hooks");
  const target = join(cwd, "operator-hook");
  writeFileSync(target, "#!/bin/sh\nnpm test\n", { mode: 0o755 });
  symlinkSync(target, join(hooks, "pre-commit"));
  const prePush = join(hooks, "pre-push");
  const original = "#!/bin/sh\n# Generated by kit\nnpm audit\n";
  writeFileSync(prePush, original, { mode: 0o755 });

  for (const command of ["check", "install", "uninstall"]) {
    const result = await runCli(cwd, ["hooks", command]);
    assert.equal(result.code, 1, `${command}: ${result.output}`);
    assert.match(result.output, /symbolic.link hook/i);
    assert.equal(readFileSync(prePush, "utf-8"), original);
    assert.equal(readFileSync(target, "utf-8"), "#!/bin/sh\nnpm test\n");
  }

  unlinkSync(join(hooks, "pre-commit"));
  writeFileSync(join(hooks, "pre-commit"), "#!/bin/sh\nnpm test\n", { mode: 0o755 });
  assert.equal((await runCli(cwd, ["hooks", "check"])).code, 0);
  const status = await runCli(cwd, ["status", "--json"]);
  assert.equal(status.code, 0);
  assert.match(status.output, /"key": "git-hooks"/);
  assert.match(status.output, /"label": "git hooks",\s*"ok": true/);
});

it("browser CLI never prints credential-bearing CDP URLs", async () => {
  const cwd = mkdtempSync(join(tmpdir(), "kit-browser-cli-credentials-"));
  dirs.push(cwd);
  mkdirSync(join(cwd, "home"));
  const server = createServer((_request, response) => {
    response.setHeader("content-type", "application/json");
    response.end('{"Browser":"Chrome"}');
  });
  await new Promise<void>((done) => server.listen(0, "127.0.0.1", done));
  try {
    const address = server.address();
    assert.ok(address && typeof address !== "string");
    const base = `http://127.0.0.1:${address.port}`;
    assert.equal((await fetch(`${base}/json/version`)).ok, true);
    writeFileSync(join(cwd, ".kit.toml"), `[browser]\nport = ${address.port}\n`);
    for (const suffix of ["operator:private-secret@", "?token=private-secret"]) {
      const url = suffix.startsWith("?")
        ? `${base}/${suffix}`
        : `http://${suffix}127.0.0.1:${address.port}`;
      for (const command of ["doctor", "cdp-url", "playwright-env"]) {
        const result = await runCli(cwd, ["browser", command, "--json"], {
          KIT_BROWSER_CDP_URL: url,
        });
        assert.ok(!result.output.includes("private-secret"), `${command}: ${result.output}`);
        assert.ok(!result.output.includes(url), `${command}: ${result.output}`);
      }
    }
  } finally {
    server.close();
  }
});
