import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { existsSync } from "node:fs";
import type { HooksConfig } from "./config.js";
import { missingHookCommands, resolveHooksDir } from "./hooks.js";

export interface HookCheckResult {
  hookName: string;
  installed: boolean;
  upToDate: boolean;
  detail: string;
}

/**
 * Check if git hooks are installed and up-to-date
 */
export async function checkHooks(
  config: HooksConfig,
  gitDir = ".git",
  cwd = process.cwd(),
): Promise<HookCheckResult[]> {
  const results: HookCheckResult[] = [];
  // The SAME resolver the writer uses. Hardcoding `<gitDir>/hooks` here meant that with an
  // external `core.hooksPath`, kit installed to one directory and reported on another: the
  // declared hooks read as "not installed" while they were installed and firing (#496).
  const hooksDir = resolveHooksDir(gitDir, cwd);

  for (const [hookName, commands] of Object.entries(config)) {
    if (!commands || commands.length === 0) {
      continue;
    }

    const result = await checkHook(hooksDir, hookName, commands);
    results.push(result);
  }

  return results;
}

/**
 * Check a single git hook
 */
async function checkHook(
  hooksDir: string,
  hookName: string,
  commands: string[],
): Promise<HookCheckResult> {
  const hookPath = resolve(hooksDir, hookName);

  // Check if hook file exists
  if (!existsSync(hookPath)) {
    return {
      hookName,
      installed: false,
      upToDate: false,
      detail: "not installed",
    };
  }

  try {
    // Read hook content
    const content = await readFile(hookPath, "utf-8");

    const missing = missingHookCommands(content, commands);
    const upToDate = missing.length === 0;

    // A Husky/Lefthook/.githooks-style hook can satisfy the contract too, as
    // long as it actually runs the commands declared in [hooks].
    if (!content.includes("# Generated by kit")) {
      return {
        hookName,
        installed: true,
        upToDate,
        detail: upToDate
          ? `externally managed; ${commands.length} configured command(s) present`
          : `not managed by kit; missing ${missing.length} configured command(s)`,
      };
    }

    return {
      hookName,
      installed: true,
      upToDate,
      detail: upToDate ? `${commands.length} command(s)` : "outdated (run kit hooks install)",
    };
  } catch (error) {
    return {
      hookName,
      installed: true,
      upToDate: false,
      detail: error instanceof Error ? error.message : String(error),
    };
  }
}

/**
 * Check if git directory exists
 */
export function isGitRepository(gitDir = ".git", cwd = process.cwd()): boolean {
  const gitPath = resolve(cwd, gitDir);
  return existsSync(gitPath);
}
