import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { existsSync, statSync } from "node:fs";
import type { HooksConfig } from "./config.js";
import { missingHookCommands, resolveHooksDir } from "./hooks.js";

export interface HookCheckResult {
  hookName: string;
  installed: boolean;
  /**
   * False when the file exists but carries no execute bit. git does not run such a
   * hook and does not say so, which makes it strictly worse than a missing hook: the
   * operator is told the gate is installed while nothing enforces it. Reported as a
   * FAIL (not a warn) on every surface — see the doctor.ts / check-run.ts mappings.
   */
  executable: boolean;
  upToDate: boolean;
  detail: string;
}

/**
 * The one status rule for a hook row, shared by `kit check --json` (check-run.ts) and
 * `kit doctor` (doctor.ts) so the two surfaces cannot disagree about what a broken hook
 * is worth. Missing or non-executable is a FAIL: git runs nothing, so nothing is
 * enforced. Present-but-outdated is a WARN: it still enforces its older command set.
 */
export function hookCheckStatus(h: HookCheckResult): "pass" | "warn" | "fail" {
  if (!h.installed || !h.executable) return "fail";
  return h.upToDate ? "pass" : "warn";
}

/**
 * Whether git would run this file as a hook. On win32 the POSIX mode bits do not
 * describe executability (git-for-windows runs hooks regardless), so the check would
 * be a false failure there and is skipped.
 */
function isExecutable(path: string): boolean {
  if (process.platform === "win32") return true;
  try {
    return (statSync(path).mode & 0o111) !== 0;
  } catch {
    return false;
  }
}

/**
 * Check if git hooks are installed and up-to-date
 */
export async function checkHooks(
  config: HooksConfig,
  gitDir = ".git",
  cwd = process.cwd(),
): Promise<HookCheckResult[]> {
  const results: HookCheckResult[] = [];
  // The SAME resolver the writer uses. Hardcoding `<gitDir>/hooks` here meant that with an
  // external `core.hooksPath`, kit installed to one directory and reported on another: the
  // declared hooks read as "not installed" while they were installed and firing (#496).
  const hooksDir = resolveHooksDir(gitDir, cwd);

  for (const [hookName, commands] of Object.entries(config)) {
    if (!commands || commands.length === 0) {
      continue;
    }

    const result = await checkHook(hooksDir, hookName, commands);
    results.push(result);
  }

  return results;
}

/**
 * Check a single git hook
 */
async function checkHook(
  hooksDir: string,
  hookName: string,
  commands: string[],
): Promise<HookCheckResult> {
  const hookPath = resolve(hooksDir, hookName);

  // Check if hook file exists
  if (!existsSync(hookPath)) {
    return {
      hookName,
      installed: false,
      executable: false,
      upToDate: false,
      detail: "not installed",
    };
  }

  // Before the content check: a hook git will not execute cannot be up-to-date, whatever
  // it contains. Checked first so the reported reason is the one that actually stops
  // enforcement, rather than a content diff the operator would fix to no effect.
  if (!isExecutable(hookPath)) {
    return {
      hookName,
      installed: true,
      executable: false,
      upToDate: false,
      detail: "not executable; git will not run it (run kit hooks install)",
    };
  }

  try {
    // Read hook content
    const content = await readFile(hookPath, "utf-8");

    const missing = missingHookCommands(content, commands);
    const upToDate = missing.length === 0;

    // A Husky/Lefthook/.githooks-style hook can satisfy the contract too, as
    // long as it actually runs the commands declared in [hooks].
    if (!content.includes("# Generated by kit")) {
      return {
        hookName,
        installed: true,
        executable: true,
        upToDate,
        detail: upToDate
          ? `externally managed; ${commands.length} configured command(s) present`
          : `not managed by kit; missing ${missing.length} configured command(s)`,
      };
    }

    return {
      hookName,
      installed: true,
      executable: true,
      upToDate,
      detail: upToDate ? `${commands.length} command(s)` : "outdated (run kit hooks install)",
    };
  } catch (error) {
    return {
      hookName,
      installed: true,
      executable: true,
      upToDate: false,
      detail: error instanceof Error ? error.message : String(error),
    };
  }
}

/**
 * Check if git directory exists
 */
export function isGitRepository(gitDir = ".git", cwd = process.cwd()): boolean {
  const gitPath = resolve(cwd, gitDir);
  return existsSync(gitPath);
}
