/**
 * BH-01, at the surfaces an operator actually reads. On POSIX, a hook file without
 * an execute bit is never run by git, so every surface must call it a failure:
 * `kit hooks check` (exit 1), `kit check --category hooks --json` (ok: false) and
 * `kit doctor --json` (a fail row). check-hooks.test.ts covers the unit; this covers the
 * wiring, which is where the three surfaces historically drifted apart.
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const adjacentCli = resolve(import.meta.dirname, "cli.js");
const CLI = existsSync(adjacentCli) ? adjacentCli : resolve(import.meta.dirname, "../dist/cli.js");

/** A repo with one declared hook, installed and then stripped of its execute bit. */
function projectWithNonExecutableHook(): string {
  const dir = mkdtempSync(join(tmpdir(), "kit-hook-exec-"));
  writeFileSync(join(dir, ".kit.toml"), 'version = 1\n\n[hooks]\npre-commit = ["npm run lint"]\n');
  writeFileSync(
    join(dir, "package.json"),
    JSON.stringify({ name: "hook-exec", version: "1.0.0", private: true }) + "\n",
  );
  const hooksDir = join(dir, ".git", "hooks");
  mkdirSync(hooksDir, { recursive: true });
  writeFileSync(join(hooksDir, "pre-commit"), "#!/bin/sh\n# Generated by kit\nnpm run lint\n", {
    mode: 0o644,
  });
  chmodSync(join(hooksDir, "pre-commit"), 0o644);
  return dir;
}

function projectWithOutdatedHook(): string {
  const dir = projectWithNonExecutableHook();
  writeFileSync(
    join(dir, ".git", "hooks", "pre-commit"),
    "#!/bin/sh\n# Generated by kit\nnpm run test\n",
    {
      mode: 0o755,
    },
  );
  chmodSync(join(dir, ".git", "hooks", "pre-commit"), 0o755);
  return dir;
}

function run(dir: string, args: string[]): { status: number | null; out: string } {
  const home = mkdtempSync(join(tmpdir(), "kit-hook-exec-home-"));
  try {
    const result = spawnSync(process.execPath, [CLI, ...args], {
      cwd: dir,
      encoding: "utf-8",
      env: {
        ...process.env,
        CI: "true",
        HOME: home,
        USERPROFILE: home,
        KIT_HIDE_HOOK_SKIP_BANNER: "1",
        KIT_IDENTITY_DIR: join(home, ".kit"),
        KIT_MEMORY_DIR: join(home, ".kit", "memory"),
      },
      timeout: 120_000,
    });
    return { status: result.status, out: `${result.stdout ?? ""}${result.stderr ?? ""}` };
  } finally {
    rmSync(home, { recursive: true, force: true });
  }
}

describe(
  "a non-executable git hook fails every reporting surface (BH-01)",
  {
    skip: process.platform === "win32",
  },
  () => {
    it("`kit hooks check` exits 1 and names the reason", { timeout: 60_000 }, () => {
      const dir = projectWithNonExecutableHook();
      try {
        const { status, out } = run(dir, ["hooks", "check"]);
        assert.equal(status, 1, out);
        assert.match(out, /not executable/);
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    });

    it("`kit check --category hooks --json` reports ok: false", { timeout: 180_000 }, () => {
      const dir = projectWithNonExecutableHook();
      try {
        const { out } = run(dir, ["check", "--category", "hooks", "--json"]);
        const report = JSON.parse(out.slice(out.indexOf("{"), out.lastIndexOf("}") + 1)) as {
          ok: boolean;
          checks: { name: string; status: string; detail: string; category: string }[];
        };
        assert.equal(report.ok, false);
        const hook = report.checks.find((c) => c.category === "hooks" && c.name === "pre-commit");
        assert.ok(hook, `no pre-commit hook row in ${out}`);
        assert.equal(hook.status, "fail");
        assert.match(hook.detail, /not executable/);
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    });

    it("`kit doctor --json` reports a fail row, not a warn", { timeout: 180_000 }, () => {
      const dir = projectWithNonExecutableHook();
      try {
        const { out } = run(dir, ["doctor", "--json"]);
        const report = JSON.parse(out.slice(out.indexOf("{"), out.lastIndexOf("}") + 1)) as {
          checks: { name: string; status: string; detail: string; category: string }[];
        };
        const hook = report.checks.find((c) => c.category === "hooks" && c.name === "pre-commit");
        assert.ok(hook, `no pre-commit hook row in ${out}`);
        assert.equal(hook.status, "fail");
        assert.match(hook.detail, /not executable/);
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    });
  },
);

it(
  "Windows does not reject hooks based on POSIX execute bits",
  {
    skip: process.platform !== "win32",
    timeout: 180_000,
  },
  () => {
    const dir = projectWithNonExecutableHook();
    try {
      const hooks = run(dir, ["hooks", "check"]);
      assert.equal(hooks.status, 0, hooks.out);
      const check = run(dir, ["check", "--category", "hooks", "--json"]);
      const checkReport = JSON.parse(
        check.out.slice(check.out.indexOf("{"), check.out.lastIndexOf("}") + 1),
      ) as { checks: { name: string; category: string; status: string }[] };
      assert.equal(checkReport.checks.find((row) => row.name === "pre-commit")?.status, "pass");
      const doctor = run(dir, ["doctor", "--json"]);
      const doctorReport = JSON.parse(
        doctor.out.slice(doctor.out.indexOf("{"), doctor.out.lastIndexOf("}") + 1),
      ) as { checks: { name: string; category: string; status: string }[] };
      assert.equal(doctorReport.checks.find((row) => row.name === "pre-commit")?.status, "pass");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  },
);

describe("an outdated git hook has one verdict across all reporting surfaces (BH-04)", () => {
  it("fails hooks check, check, and doctor", { timeout: 180_000 }, () => {
    const dir = projectWithOutdatedHook();
    try {
      const hooks = run(dir, ["hooks", "check"]);
      assert.equal(hooks.status, 1, hooks.out);
      const check = run(dir, ["check", "--category", "hooks", "--json"]);
      const checkReport = JSON.parse(
        check.out.slice(check.out.indexOf("{"), check.out.lastIndexOf("}") + 1),
      ) as {
        ok: boolean;
        checks: { name: string; category: string; status: string }[];
      };
      assert.equal(check.status, 1, check.out);
      assert.equal(checkReport.ok, false);
      assert.equal(checkReport.checks.find((row) => row.name === "pre-commit")?.status, "fail");
      const doctor = run(dir, ["doctor", "--json"]);
      const doctorReport = JSON.parse(
        doctor.out.slice(doctor.out.indexOf("{"), doctor.out.lastIndexOf("}") + 1),
      ) as { ok: boolean; checks: { name: string; category: string; status: string }[] };
      assert.equal(doctor.status, 1, doctor.out);
      assert.equal(doctorReport.ok, false);
      assert.equal(doctorReport.checks.find((row) => row.name === "pre-commit")?.status, "fail");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
