import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { existsSync } from "node:fs";
import type { HooksConfig } from "./config.js";

export interface HookCheckResult {
  hookName: string;
  installed: boolean;
  upToDate: boolean;
  detail: string;
}

/**
 * Check if git hooks are installed and up-to-date
 */
export async function checkHooks(
  config: HooksConfig,
  gitDir = ".git",
): Promise<HookCheckResult[]> {
  const results: HookCheckResult[] = [];
  const hooksDir = resolve(process.cwd(), gitDir, "hooks");

  for (const [hookName, commands] of Object.entries(config)) {
    if (!commands || commands.length === 0) {
      continue;
    }

    const result = await checkHook(hooksDir, hookName, commands);
    results.push(result);
  }

  return results;
}

/**
 * Check a single git hook
 */
async function checkHook(
  hooksDir: string,
  hookName: string,
  commands: string[],
): Promise<HookCheckResult> {
  const hookPath = resolve(hooksDir, hookName);

  // Check if hook file exists
  if (!existsSync(hookPath)) {
    return {
      hookName,
      installed: false,
      upToDate: false,
      detail: "not installed",
    };
  }

  try {
    // Read hook content
    const content = await readFile(hookPath, "utf-8");

    // Check if it's a kit-generated hook
    if (!content.includes("# Generated by kit")) {
      return {
        hookName,
        installed: true,
        upToDate: false,
        detail: "not managed by kit",
      };
    }

    // Check if commands match
    const upToDate = commands.every((cmd) => content.includes(cmd));

    return {
      hookName,
      installed: true,
      upToDate,
      detail: upToDate
        ? `${commands.length} command(s)`
        : "outdated (run kit hooks install)",
    };
  } catch (error) {
    return {
      hookName,
      installed: true,
      upToDate: false,
      detail: error instanceof Error ? error.message : String(error),
    };
  }
}

/**
 * Check if git directory exists
 */
export function isGitRepository(gitDir = ".git"): boolean {
  const gitPath = resolve(process.cwd(), gitDir);
  return existsSync(gitPath);
}
