import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runDoctor } from "./doctor.js";
import { checkGitHookFloor } from "./check-security.js";

describe("doctor and security agree about hook wrapper health (BH-05)", () => {
  it("warns when the wrapper points into a git working tree", async () => {
    const home = mkdtempSync(join(tmpdir(), "kit-wrapper-home-"));
    const repo = join(home, "repo");
    const previousHome = process.env.HOME;
    const previousCwd = process.cwd();
    try {
      mkdirSync(join(home, ".kit", "bin"), { recursive: true });
      mkdirSync(join(repo, ".git", "hooks"), { recursive: true });
      mkdirSync(join(repo, "dist"), { recursive: true });
      const entry = join(repo, "dist", "cli.js");
      writeFileSync(entry, "// fixture\n");
      writeFileSync(join(repo, ".kit.toml"), "version = 1\n");
      writeFileSync(
        join(repo, ".git", "hooks", "pre-commit"),
        "#!/bin/sh\n# Generated by kit\nsecurity scan-staged\n",
        { mode: 0o755 },
      );
      writeFileSync(
        join(home, ".kit", "bin", "kit"),
        `#!/bin/sh\n# kit-managed wrapper (do not edit)\nexec "${process.execPath}" "${entry}" "$@"\n`,
        { mode: 0o755 },
      );
      process.env.HOME = home;
      process.chdir(repo);

      const security = await checkGitHookFloor(repo);
      assert.equal(security.status, "warn");
      assert.match(security.detail, /working tree/);
      const doctor = await runDoctor({}, repo);
      const wrapper = doctor.checks.find((check) => check.name === "hook wrapper");
      assert.ok(wrapper);
      assert.equal(wrapper.status, security.status);
      assert.equal(wrapper.detail, security.detail);
    } finally {
      process.chdir(previousCwd);
      if (previousHome === undefined) delete process.env.HOME;
      else process.env.HOME = previousHome;
      rmSync(home, { recursive: true, force: true });
    }
  });
});
