/**
 * kit's declared FLAG SURFACE — the flags each command accepts, checked once at dispatch
 * instead of once per handler.
 *
 * GENERATED. Regenerate with:  node scripts/derive-command-flags.mjs --emit
 * `flag-surface.test.ts` fails when this file drifts from the source scan, so the table can
 * never quietly fall behind a new flag.
 *
 * WHY A TABLE AND NOT 45 PER-MODULE GUARDS: the same reasoning as `read-only-surface.ts`. Two
 * modules validated their flags after #487 and 43 did not, and the class is not theoretical —
 * `kit check --category security` ran the FULL check for six majors because nothing rejected the
 * flag, and `kit upgrade --self.` (trailing period) fell through to the lock-file path, rewrote
 * every `installedAt`, installed nothing, and printed the success line. Sweeping 43 handlers
 * would fix today and rot tomorrow: the defect is that nothing ENUMERATED which flags each
 * command accepts, so "did we cover everything?" had no answer. This table is that answer.
 *
 * HOW THE SETS ARE DERIVED (scripts/derive-command-flags.mjs): every `--flag` literal in the
 * command's own module, plus the flag literals its DIRECT imports hand to an argv reader
 * (`hasFlag` / `flagValue` / `flagInt` / `includes` / `indexOf` / `===` / `startsWith`), plus
 * every flag `docs/COMMANDS.md` documents for that verb. Depth-1 is deliberate: an allowlist
 * built from a handler file alone rejected `kit check --attest` and `--no-auto-install`, both
 * documented and both read one import away in `cli-checks-shared.ts`.
 *
 * The sets ERR TOWARD ACCEPTING. A flag kit only passes to a subprocess (`--severity` for trivy)
 * can appear here; over-accepting leaves a working invocation working, while under-accepting
 * breaks one. The guard's job is to catch what does NOTHING, not to police spelling.
 *
 * GLOBAL_FLAGS are not listed: the guard unions them in, so a global can never be missing
 * per-verb — the omission that made `kit check --read-only` exit 1 without running.
 *
 * ADDING A COMMAND: run the generator. A verb missing from this table is not "allowed to accept
 * anything", it is unvalidated — `self-audit` reports it as such.
 */

export const COMMAND_FLAGS: Record<string, readonly string[]> = {
  add: [
    "--auto",
    "--aws-region",
    "--category",
    "--cf-worker",
    "--dry-run",
    "--enforce-tests",
    "--fail-on-warning",
    "--fail-on-worse",
    "--fix",
    "--fly-app",
    "--force",
    "--force-history",
    "--from",
    "--github-repo",
    "--help",
    "--host",
    "--install",
    "--json",
    "--keep-commented",
    "--key",
    "--key-id",
    "--lenient",
    "--list",
    "--minimal",
    "--mode",
    "--no-clean",
    "--no-recommended",
    "--no-setup",
    "--no-triage",
    "--non-interactive",
    "--path",
    "--pin",
    "--plan",
    "--project",
    "--purge",
    "--railway-service",
    "--recommended",
    "--retry-count",
    "--secrets-only",
    "--service",
    "--services",
    "--stdin",
    "--store",
    "--strict",
    "--target-env",
    "--to",
    "--value",
    "--vercel-scope",
    "--verify",
    "--via",
    "--with-migrate",
    "--yes",
  ],
  adr: [],
  "agent-audit": ["--attest", "--json", "--mode", "--no-auto-install", "--non-interactive"],
  "agent-config": [
    "--broker-gate",
    "--help",
    "--install-gate",
    "--limit",
    "--mode",
    "--no-install-gate",
  ],
  airgap: ["--json"],
  analyze: [
    "--attest",
    "--claude",
    "--fail-on-warning",
    "--format",
    "--json",
    "--list-rules",
    "--list-standards",
    "--no-auto-install",
    "--rules",
    "--verify",
    "--write",
  ],
  audit: [
    "--all",
    "--external",
    "--format",
    "--json",
    "--key",
    "--limit",
    "--operation",
    "--require-external",
    "--since-days",
    "--strict",
  ],
  auth: [
    "--account",
    "--issuer",
    "--json",
    "--list-scopes",
    "--non-interactive",
    "--overwrite",
    "--scope",
    "--ttl-minutes",
  ],
  baseline: ["--category", "--enforce", "--help", "--json"],
  bootstrap: ["--json", "--minimal", "--no-memory", "--profile"],
  broker: ["--force", "--gate", "--json"],
  browser: ["--help", "--json"],
  check: [
    "--attest",
    "--category",
    "--enforce-tests",
    "--fail-on-warning",
    "--fail-on-worse",
    "--json",
    "--key",
    "--lenient",
    "--no-auto-install",
    "--pin",
    "--read-only",
    "--self",
    "--strict",
  ],
  ci: [
    "--attest",
    "--fail-on-warning",
    "--format",
    "--init",
    "--json",
    "--lenient",
    "--no-auto-install",
    "--strict",
    "--write",
  ],
  clone: [
    "--env",
    "--install",
    "--list",
    "--minimal",
    "--mode",
    "--no-recommended",
    "--no-setup",
    "--non-interactive",
    "--recommended",
    "--services",
    "--skip-install",
    "--store",
    "--verify",
    "--with-migrate",
    "--yes",
  ],
  config: ["--allow-comment-loss", "--check", "--dry-run", "--force", "--help", "--json"],
  context: ["--format", "--json", "--prompt", "--require-declaration"],
  coverage: [
    "--attest",
    "--claude",
    "--fail-on-warning",
    "--format",
    "--json",
    "--list-rules",
    "--list-standards",
    "--no-auto-install",
    "--rules",
    "--standard",
    "--verify",
    "--write",
  ],
  "create-plugin": [
    "--env",
    "--install",
    "--list",
    "--minimal",
    "--mode",
    "--no-recommended",
    "--no-setup",
    "--non-interactive",
    "--recommended",
    "--services",
    "--skip-install",
    "--store",
    "--verify",
    "--with-migrate",
    "--yes",
  ],
  design: ["--enforce", "--json"],
  doctor: [
    "--auto",
    "--aws-region",
    "--category",
    "--cf-worker",
    "--dry-run",
    "--enforce-tests",
    "--fail-on-warning",
    "--fail-on-worse",
    "--fix",
    "--fly-app",
    "--force",
    "--force-history",
    "--from",
    "--github-repo",
    "--help",
    "--host",
    "--install",
    "--json",
    "--keep-commented",
    "--key",
    "--key-id",
    "--lenient",
    "--list",
    "--minimal",
    "--mode",
    "--no-clean",
    "--no-recommended",
    "--no-setup",
    "--no-triage",
    "--non-interactive",
    "--path",
    "--pin",
    "--plan",
    "--project",
    "--purge",
    "--railway-service",
    "--recommended",
    "--retry-count",
    "--secrets-only",
    "--service",
    "--services",
    "--stdin",
    "--store",
    "--strict",
    "--target-env",
    "--to",
    "--value",
    "--vercel-scope",
    "--verify",
    "--via",
    "--with-migrate",
    "--yes",
  ],
  env: ["--compare", "--json", "--missing", "--non-interactive", "--show-values"],
  escalate: ["--broker-gate", "--help", "--limit", "--mode", "--no-install-gate"],
  fix: [],
  "gate-bash": ["--all", "--allow-scripts-pending", "--call", "--dry-run", "--format", "--with"],
  "gate-egress": ["--all", "--allow-scripts-pending", "--call", "--dry-run", "--format", "--with"],
  "gate-env": ["--all", "--allow-scripts-pending", "--call", "--dry-run", "--format", "--with"],
  "gate-fs": ["--all", "--allow-scripts-pending", "--call", "--dry-run", "--format", "--with"],
  "gha-audit": ["--json"],
  governance: ["--broker-gate", "--help", "--limit", "--mode", "--no-install-gate"],
  guard: ["--all", "--allow-scripts-pending", "--call", "--dry-run", "--help", "--with"],
  "guard-observe": ["--all", "--allow-scripts-pending", "--call", "--dry-run", "--help", "--with"],
  heal: ["--agent", "--dry-run", "--help"],
  health: ["--attest", "--json", "--mode", "--no-auto-install", "--non-interactive"],
  hooks: ["--force", "--non-interactive"],
  identity: ["--public"],
  ingest: ["--attest", "--json", "--mode", "--no-auto-install", "--non-interactive"],
  init: [
    "--auto",
    "--aws-region",
    "--category",
    "--cf-worker",
    "--dry-run",
    "--enforce-tests",
    "--fail-on-warning",
    "--fail-on-worse",
    "--fix",
    "--fly-app",
    "--force",
    "--force-history",
    "--from",
    "--github-repo",
    "--help",
    "--host",
    "--install",
    "--json",
    "--keep-commented",
    "--key",
    "--key-id",
    "--lenient",
    "--list",
    "--minimal",
    "--mode",
    "--no-clean",
    "--no-recommended",
    "--no-setup",
    "--no-triage",
    "--non-interactive",
    "--path",
    "--pin",
    "--plan",
    "--project",
    "--purge",
    "--railway-service",
    "--recommended",
    "--retry-count",
    "--secrets-only",
    "--service",
    "--services",
    "--stdin",
    "--store",
    "--strict",
    "--target-env",
    "--to",
    "--value",
    "--vercel-scope",
    "--verify",
    "--via",
    "--with-migrate",
    "--yes",
  ],
  insight: ["--json"],
  install: ["--no-triage"],
  login: ["--json", "--non-interactive", "--plan", "--retry-count", "--service"],
  map: ["--budget", "--co-change", "--depth", "--help", "--json", "--name-only", "--no-merges"],
  mcp: ["--from-env", "--paste"],
  memory: [
    "--all",
    "--area",
    "--auto",
    "--body",
    "--branch",
    "--brief",
    "--changed",
    "--command",
    "--confidence",
    "--expect",
    "--force",
    "--fresh",
    "--global",
    "--heatmap",
    "--help",
    "--include-quarantined",
    "--injection",
    "--json",
    "--kind",
    "--limit",
    "--no-statusline",
    "--obsidian",
    "--passphrase",
    "--project",
    "--provenance",
    "--pull-cmd",
    "--push-cmd",
    "--quarantine",
    "--reason",
    "--ref",
    "--remap-project",
    "--remote",
    "--reverses",
    "--scaffold",
    "--scope",
    "--session",
    "--stale",
    "--status",
    "--strict",
    "--supersedes",
    "--title",
    "--to",
    "--tokens",
    "--verify-file",
    "--verify-http",
  ],
  open: [
    "--env",
    "--install",
    "--list",
    "--minimal",
    "--mode",
    "--no-recommended",
    "--no-setup",
    "--non-interactive",
    "--recommended",
    "--services",
    "--skip-install",
    "--store",
    "--verify",
    "--with-migrate",
    "--yes",
  ],
  panic: ["--no-checklist", "--reason"],
  pkg: ["--agent", "--dry-run", "--help"],
  plugin: ["--help", "--tag"],
  policy: [
    "--env",
    "--force",
    "--json",
    "--key",
    "--label",
    "--list",
    "--remove",
    "--strict",
    "--ttl",
  ],
  profile: ["--gate", "--json", "--key", "--out"],
  review: [
    "--attest",
    "--category",
    "--enforce",
    "--enforce-tests",
    "--fail-on-warning",
    "--json",
    "--lenient",
    "--no-auto-install",
    "--stages",
    "--strict",
  ],
  run: [
    "--env",
    "--install",
    "--list",
    "--minimal",
    "--mode",
    "--no-recommended",
    "--no-setup",
    "--non-interactive",
    "--recommended",
    "--services",
    "--skip-install",
    "--store",
    "--verify",
    "--with-migrate",
    "--yes",
  ],
  sbom: ["--agent", "--format"],
  scan: ["--json", "--list-delegates", "--sarif", "--strict", "--update-baseline"],
  secrets: [
    "--auto",
    "--aws-region",
    "--cf-worker",
    "--dry-run",
    "--fix",
    "--fly-app",
    "--force",
    "--force-history",
    "--from",
    "--from-cli",
    "--github-repo",
    "--help",
    "--host",
    "--keep-commented",
    "--key-id",
    "--mode",
    "--no-clean",
    "--non-interactive",
    "--path",
    "--project",
    "--propagate",
    "--purge",
    "--railway-service",
    "--random",
    "--secrets-only",
    "--stdin",
    "--store",
    "--target",
    "--target-env",
    "--to",
    "--value",
    "--vercel-scope",
    "--via",
    "--yes",
  ],
  security: [
    "--base",
    "--deep",
    "--exclude",
    "--fix",
    "--format",
    "--head",
    "--json",
    "--non-interactive",
    "--only",
    "--recursive",
    "--skip",
    "--vs-baseline",
  ],
  "self-audit": [
    "--attest",
    "--claude",
    "--fail-on-warning",
    "--format",
    "--json",
    "--list-rules",
    "--list-standards",
    "--no-auto-install",
    "--only",
    "--rules",
    "--verify",
    "--write",
  ],
  sentinel: ["--force", "--json", "--label", "--limit", "--schedule", "--state"],
  setup: [
    "--auto",
    "--aws-region",
    "--category",
    "--cf-worker",
    "--dry-run",
    "--enforce-tests",
    "--fail-on-warning",
    "--fail-on-worse",
    "--fix",
    "--fly-app",
    "--force",
    "--force-history",
    "--from",
    "--github-repo",
    "--help",
    "--host",
    "--install",
    "--json",
    "--keep-commented",
    "--key",
    "--key-id",
    "--lenient",
    "--list",
    "--minimal",
    "--mode",
    "--no-clean",
    "--no-recommended",
    "--no-setup",
    "--no-triage",
    "--non-interactive",
    "--path",
    "--pin",
    "--plan",
    "--project",
    "--purge",
    "--railway-service",
    "--recommended",
    "--retry-count",
    "--secrets-only",
    "--service",
    "--services",
    "--stdin",
    "--store",
    "--strict",
    "--target-env",
    "--to",
    "--value",
    "--vercel-scope",
    "--verify",
    "--via",
    "--with-migrate",
    "--yes",
  ],
  skill: ["--gate", "--json", "--path", "--runtime", "--update-snapshot"],
  skills: ["--broker-gate", "--help", "--limit", "--mode", "--no-install-gate"],
  slopsquat: ["--fail-on"],
  standards: ["--category", "--enforce", "--help", "--json"],
  status: ["--attest", "--json", "--mode", "--no-auto-install", "--non-interactive"],
  statusline: ["--broker-gate", "--help", "--limit", "--mode", "--no-install-gate"],
  "supply-chain": ["--attest", "--json", "--mode", "--no-auto-install", "--non-interactive"],
  team: ["--broker-gate", "--help", "--limit", "--mode", "--no-install-gate", "--role"],
  tools: ["--json", "--latest"],
  triage: [
    "--cached",
    "--deep",
    "--help",
    "--json",
    "--name-only",
    "--pin",
    "--sandbox",
    "--scan-bytes",
    "--tools",
  ],
  upgrade: ["--self"],
  "verify-provenance": ["--bundle", "--identity", "--issuer", "--offline", "--trusted-root"],
  whoami: ["--attest", "--json", "--mode", "--no-auto-install", "--non-interactive"],
};

/**
 * The flags a verb accepts, or null when the verb is not in the table (unvalidated rather
 * than unrestricted — dispatch skips the check and self-audit reports the gap).
 */
export function flagsForCommand(verb: string): readonly string[] | null {
  return COMMAND_FLAGS[verb] ?? null;
}
