/**
 * The git-hook floor has to report where it is and whether it can fail.
 *
 * Both properties were measured missing (#496, #497), and both failure modes are silent, so the
 * tests drive the real thing: temp repos with a real `core.hooksPath`, real generated hooks, and
 * the compiled CLI for the paths an operator actually types.
 *
 * The measurement that produced #496: a second checkout copied from the first inherits the
 * first's ABSOLUTE `core.hooksPath`, so its hooks live in the other clone's tree. Deleting that
 * unrelated directory removed the gate — a staged fake credential that had been blocked
 * committed cleanly afterwards, exit 0, with every kit report silent. #497: `kit hooks add
 * context-check` installed a pre-push gate that, with no `[context]` block, passes every push.
 */

import { describe, it, beforeEach, afterEach } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync, mkdirSync, writeFileSync, realpathSync } from "node:fs";
import { execFile, execFileSync } from "node:child_process";
import { promisify } from "node:util";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { describeHookFloor, judgeHookFloor, type HookFloorReport } from "./hook-floor.js";

const exec = promisify(execFile);
const CLI_PATH = resolve(dirname(fileURLToPath(import.meta.url)), "cli.js");

/** A generated-looking kit hook body, matching what installHooks writes. */
const kitHook = (command: string): string =>
  ["#!/bin/sh", "# Generated by kit", "# Hook: test", `"$HOME/.kit/bin/kit" ${command}`, ""].join(
    "\n",
  );

function git(cwd: string, ...args: string[]): void {
  execFileSync("git", ["-C", cwd, ...args], { stdio: "ignore" });
}

describe("hook floor — describeHookFloor", () => {
  let dirs: string[] = [];
  const repo = (): string => {
    const d = realpathSync(mkdtempSync(join(tmpdir(), "kit-floor-")));
    dirs.push(d);
    execFileSync("git", ["init", "-q", d], { stdio: "ignore" });
    return d;
  };

  beforeEach(() => {
    dirs = [];
  });
  afterEach(() => {
    for (const d of dirs) rmSync(d, { recursive: true, force: true });
  });

  it("reports the repo-local floor and the kit hooks in it", () => {
    const r = repo();
    writeFileSync(join(r, ".git", "hooks", "pre-commit"), kitHook("security scan-staged"));
    const f = describeHookFloor(r);
    assert.equal(f.external, false);
    assert.equal(f.exists, true);
    assert.equal(f.hooksPath, undefined);
    assert.deepEqual(f.installed, ["secret-scan"]);
    assert.deepEqual(f.unarmed, []);
  });

  it("does not claim a hand-written hook as kit's floor", () => {
    const r = repo();
    writeFileSync(join(r, ".git", "hooks", "pre-commit"), "#!/bin/sh\nnpm test\n");
    assert.deepEqual(describeHookFloor(r).installed, []);
  });

  it("reports a floor that resolves OUTSIDE the repo", () => {
    const r = repo();
    const elsewhere = realpathSync(mkdtempSync(join(tmpdir(), "kit-floor-other-")));
    dirs.push(elsewhere);
    mkdirSync(join(elsewhere, "hooks"));
    writeFileSync(join(elsewhere, "hooks", "pre-commit"), kitHook("security scan-staged"));
    git(r, "config", "core.hooksPath", join(elsewhere, "hooks"));

    const f = describeHookFloor(r);
    assert.equal(f.external, true, "a hooks dir in another tree is external");
    assert.equal(f.dir, join(elsewhere, "hooks"));
    assert.equal(f.hooksPath, join(elsewhere, "hooks"));
    assert.deepEqual(f.installed, ["secret-scan"]);

    const v = judgeHookFloor(f);
    assert.equal(v.status, "warn");
    assert.match(v.detail, /OUTSIDE/);
    assert.match(v.detail, /silently removes the gate/);
  });

  it("a repo-relative hooksPath inside the repo is NOT external (the husky/.githooks case)", () => {
    const r = repo();
    mkdirSync(join(r, ".githooks"));
    writeFileSync(join(r, ".githooks", "pre-commit"), kitHook("security scan-staged"));
    git(r, "config", "core.hooksPath", ".githooks");

    const f = describeHookFloor(r);
    assert.equal(f.external, false);
    assert.equal(f.exists, true);
    assert.equal(judgeHookFloor(f).status, "pass");
  });

  it("a hooksPath pointing at a deleted directory means every hook is OFF", () => {
    const r = repo();
    const gone = join(tmpdir(), "kit-floor-deleted-does-not-exist", "hooks");
    git(r, "config", "core.hooksPath", gone);

    const f = describeHookFloor(r);
    assert.equal(f.exists, false);
    assert.deepEqual(f.installed, [], "nothing can be installed in a directory that is gone");

    const v = judgeHookFloor(f);
    assert.equal(v.status, "fail");
    assert.equal(v.severity, "high");
    assert.match(v.detail, /does not exist — every git hook is OFF/);
  });

  it("context-check with no [context] block is reported as unarmed", () => {
    const r = repo();
    writeFileSync(join(r, ".git", "hooks", "pre-push"), kitHook("context check"));
    const f = describeHookFloor(r, undefined);
    assert.deepEqual(f.installed, ["context-check"]);
    assert.deepEqual(f.unarmed, ["context-check"]);

    const v = judgeHookFloor(f);
    assert.equal(v.status, "fail");
    assert.match(v.detail, /cannot fail/);
  });

  it("context-check with a [context] block is armed", () => {
    const r = repo();
    writeFileSync(join(r, ".git", "hooks", "pre-push"), kitHook("context check"));
    const f = describeHookFloor(r, { context: { github: { org: "acme" } } });
    assert.deepEqual(f.unarmed, []);
    assert.equal(judgeHookFloor(f).status, "pass");
  });
});

describe("hook floor — judgeHookFloor policy", () => {
  const base: HookFloorReport = {
    dir: "/repo/.git/hooks",
    external: false,
    exists: true,
    installed: [],
    unarmed: [],
  };

  it("skips when the repo has no kit-managed hooks — no floor is claimed", () => {
    const v = judgeHookFloor(base);
    assert.equal(v.status, "skip");
    assert.equal(v.severity, undefined);
  });

  it("ranks a dangling hooksPath above everything else", () => {
    const v = judgeHookFloor({
      ...base,
      hooksPath: "/gone/hooks",
      dir: "/gone/hooks",
      exists: false,
      external: true,
      installed: ["secret-scan"],
      unarmed: ["context-check"],
    });
    assert.equal(v.status, "fail");
    assert.match(v.detail, /does not exist/);
  });

  it("ranks an unarmed gate above an external location", () => {
    const v = judgeHookFloor({
      ...base,
      external: true,
      hooksPath: "/other/hooks",
      installed: ["context-check"],
      unarmed: ["context-check"],
    });
    assert.equal(v.status, "fail");
    assert.match(v.detail, /cannot fail/);
  });

  it("passes with the hooks named, so the report says what is actually wired", () => {
    const v = judgeHookFloor({ ...base, installed: ["secret-scan", "post-pull-audit"] });
    assert.equal(v.status, "pass");
    assert.match(v.detail, /secret-scan, post-pull-audit/);
  });
});

describe("hook floor — compiled CLI", () => {
  let repoDir = "";
  let extras: string[] = [];

  const runCli = async (
    args: string[],
    cwd: string,
  ): Promise<{ exitCode: number; stdout: string; stderr: string }> => {
    try {
      const { stdout, stderr } = await exec(process.execPath, [CLI_PATH, ...args], {
        cwd,
        env: { ...process.env, KIT_HIDE_HOOK_SKIP_BANNER: "1", KIT_AUDIT_ANCHOR: "0" },
        timeout: 60_000,
      });
      return { exitCode: 0, stdout: stdout ?? "", stderr: stderr ?? "" };
    } catch (err: unknown) {
      const e = err as { code?: number; stdout?: string; stderr?: string };
      return {
        exitCode: typeof e.code === "number" ? e.code : 1,
        stdout: e.stdout ?? "",
        stderr: e.stderr ?? "",
      };
    }
  };

  beforeEach(() => {
    repoDir = realpathSync(mkdtempSync(join(tmpdir(), "kit-floor-cli-")));
    extras = [];
    execFileSync("git", ["init", "-q", repoDir], { stdio: "ignore" });
    writeFileSync(join(repoDir, ".kit.toml"), '[tools]\nnode = "22"\n');
  });
  afterEach(() => {
    rmSync(repoDir, { recursive: true, force: true });
    for (const d of extras) rmSync(d, { recursive: true, force: true });
  });

  it("refuses to install context-check with no [context] — a gate that cannot fail", async () => {
    const r = await runCli(["hooks", "add", "context-check", "--non-interactive"], repoDir);
    assert.equal(r.exitCode, 1);
    assert.match(r.stderr, /refusing to install context-check/);
    assert.match(r.stderr, /kit context check/);
    assert.equal(describeHookFloor(repoDir).installed.length, 0, "nothing was installed");
  });

  it("--force installs it anyway, for someone about to declare the block", async () => {
    const r = await runCli(
      ["hooks", "add", "context-check", "--force", "--non-interactive"],
      repoDir,
    );
    assert.equal(r.exitCode, 0, r.stderr);
    assert.deepEqual(describeHookFloor(repoDir).installed, ["context-check"]);
  });

  it("prints a test hint for the hook it installed, not secret-scan's for everything", async () => {
    const secret = await runCli(["hooks", "add", "secret-scan", "--non-interactive"], repoDir);
    assert.match(secret.stdout, /stage a file containing sk_test/);

    const merge = await runCli(["hooks", "add", "post-pull-audit", "--non-interactive"], repoDir);
    assert.match(merge.stdout, /merge or pull a branch/);
    assert.doesNotMatch(merge.stdout, /stage a file containing sk_test/);
  });

  it("names the directory when the floor lands outside the repo", async () => {
    const elsewhere = realpathSync(mkdtempSync(join(tmpdir(), "kit-floor-ext-")));
    extras.push(elsewhere);
    mkdirSync(join(elsewhere, "hooks"));
    execFileSync("git", ["-C", repoDir, "config", "core.hooksPath", join(elsewhere, "hooks")], {
      stdio: "ignore",
    });

    const r = await runCli(["hooks", "add", "secret-scan", "--non-interactive"], repoDir);
    assert.equal(r.exitCode, 0, r.stderr);
    assert.match(r.stdout, /OUTSIDE this repo/);
    assert.match(r.stdout, new RegExp(elsewhere.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
    assert.match(r.stdout, /git config --unset core\.hooksPath/);
  });

  it("the security gate reports the floor instead of staying silent", async () => {
    writeFileSync(join(repoDir, ".git", "hooks", "pre-push"), kitHook("context check"));
    const r = await runCli(["check", "--category", "security", "--json"], repoDir);
    const rows = JSON.parse(r.stdout) as {
      checks?: Array<{ name: string; status: string; detail: string }>;
    };
    const row = (rows.checks ?? []).find((x) => x.name === "git hook floor");
    assert.ok(row, "kit check must have a git hook floor row");
    assert.equal(row.status, "fail");
    assert.match(row.detail, /cannot fail/);
  });

  it("an installed hook in an external dir is not reported as missing (reader/writer agree)", async () => {
    const elsewhere = realpathSync(mkdtempSync(join(tmpdir(), "kit-floor-agree-")));
    extras.push(elsewhere);
    mkdirSync(join(elsewhere, "hooks"));
    execFileSync("git", ["-C", repoDir, "config", "core.hooksPath", join(elsewhere, "hooks")], {
      stdio: "ignore",
    });
    writeFileSync(
      join(repoDir, ".kit.toml"),
      '[tools]\nnode = "22"\n\n[hooks]\npre-commit = ["kit security scan-staged"]\n',
    );

    const install = await runCli(["hooks", "install", "--non-interactive"], repoDir);
    assert.equal(install.exitCode, 0, install.stderr);

    // Before the fix the status reader looked at <repo>/.git/hooks — empty — and called an
    // installed, firing hook missing.
    const status = await runCli(["hooks"], repoDir);
    assert.doesNotMatch(status.stdout + status.stderr, /missing/i);
  });
});
