import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { installHooks, uninstallHooks } from "./hooks.js";

async function fixture(): Promise<{ base: string; gitDir: string; hooksDir: string }> {
  const base = await mkdtemp(join(tmpdir(), "kit-hooks-uninstall-"));
  const gitDir = join(base, ".git");
  const hooksDir = join(gitDir, "hooks");
  await mkdir(hooksDir, { recursive: true });
  return { base, gitDir, hooksDir };
}

describe("hook removal edge cases", () => {
  it("removes only the named hooks, leaving the bypass-detector pair behind", async () => {
    const { base, gitDir, hooksDir } = await fixture();
    try {
      await installHooks({ "pre-push": ["npm audit"] }, gitDir);
      assert.ok(existsSync(join(hooksDir, "post-commit")));

      await uninstallHooks(["pre-push"], gitDir);

      // installHooks writes the sentinel pair unconditionally; uninstall does NOT
      // infer them. This is why the CLI has to add pre-commit/post-commit to the
      // removal list itself — a half-removed pair makes post-commit report every
      // later commit as a --no-verify bypass forever.
      assert.ok(existsSync(join(hooksDir, "post-commit")));
      assert.ok(existsSync(join(hooksDir, "pre-commit")));
    } finally {
      await rm(base, { recursive: true, force: true });
    }
  });

  it("is idempotent for a repeated name within one call", async () => {
    const { base, gitDir, hooksDir } = await fixture();
    try {
      await writeFile(join(hooksDir, "pre-commit"), "#!/bin/sh\n# Generated by kit\n", "utf-8");

      const results = await uninstallHooks(["pre-commit", "pre-commit"], gitDir);

      // The CLI de-dupes with a Set, but a duplicate reaching here must not turn the
      // second pass into a "failed" (ENOENT) and fail the whole command.
      assert.equal(results[0].action, "installed");
      assert.equal(results[1].action, "skipped");
      assert.equal(results[1].detail, "not found");
    } finally {
      await rm(base, { recursive: true, force: true });
    }
  });

  it("refuses a symlinked removal set before deleting any hook", async () => {
    const { base, gitDir, hooksDir } = await fixture();
    try {
      await writeFile(join(hooksDir, "pre-push"), "#!/bin/sh\n# Generated by kit\n", {
        mode: 0o755,
      });
      await writeFile(join(base, "operator-script"), "#!/bin/sh\n", { mode: 0o755 });
      await symlink(join(base, "operator-script"), join(hooksDir, "pre-commit"));
      const results = await uninstallHooks(["pre-push", "pre-commit"], gitDir, base);
      assert.ok(results.some((result) => result.action === "failed"));
      assert.equal(existsSync(join(hooksDir, "pre-push")), true);
    } finally {
      await rm(base, { recursive: true, force: true });
    }
  });
});

describe("hook removal safety", () => {
  it("returns an empty list for no names and never creates the hooks directory", async () => {
    const base = await mkdtemp(join(tmpdir(), "kit-hooks-uninstall-empty-"));
    const gitDir = join(base, ".git");
    try {
      assert.deepEqual(await uninstallHooks([], gitDir), []);

      // Unlike installHooks, uninstall must not mkdir anything: reporting "not found"
      // for a repo with no hooks dir is the correct read-only outcome.
      const results = await uninstallHooks(["pre-commit"], gitDir);
      assert.equal(results[0].action, "skipped");
      assert.equal(results[0].detail, "not found");
      assert.ok(!existsSync(join(gitDir, "hooks")));
    } finally {
      await rm(base, { recursive: true, force: true });
    }
  });

  it("reports a failure instead of throwing when the hook path is a directory", async () => {
    const { base, gitDir, hooksDir } = await fixture();
    try {
      await mkdir(join(hooksDir, "pre-commit"), { recursive: true });

      const results = await uninstallHooks(["pre-commit", "pre-push"], gitDir);

      // Never throw: one unremovable entry must not abort the remaining names, and
      // the reason has to reach the operator rather than a stack trace.
      assert.equal(results[0].action, "failed");
      assert.ok(results[0].detail.length > 0);
      assert.equal(results[1].action, "skipped");
      assert.ok(existsSync(join(hooksDir, "pre-commit")));
    } finally {
      await rm(base, { recursive: true, force: true });
    }
  });

  it("rejects a traversing hook name without touching the target", async () => {
    const { base, gitDir } = await fixture();
    try {
      const outside = join(gitDir, "kit-uninstall-traversal-target");
      await writeFile(outside, "not a hook\n", "utf-8");

      const [res] = await uninstallHooks(["../kit-uninstall-traversal-target"], gitDir);

      assert.equal(res.action, "failed");
      assert.match(res.detail, /invalid hook name/i);
      assert.ok(existsSync(outside));
    } finally {
      await rm(base, { recursive: true, force: true });
    }
  });
});

describe("hook removal mode and install containment", () => {
  it("refuses to delete hooks while read-only mode is active", async () => {
    const { base, gitDir, hooksDir } = await fixture();
    const prior = process.env.KIT_READ_ONLY;
    try {
      await writeFile(join(hooksDir, "pre-commit"), "#!/bin/sh\n", "utf-8");
      process.env.KIT_READ_ONLY = "1";

      const [res] = await uninstallHooks(["pre-commit"], gitDir, base);

      assert.equal(res.action, "failed");
      assert.match(res.detail, /read-only mode active/);
      assert.ok(existsSync(join(hooksDir, "pre-commit")));
    } finally {
      if (prior === undefined) delete process.env.KIT_READ_ONLY;
      else process.env.KIT_READ_ONLY = prior;
      await rm(base, { recursive: true, force: true });
    }
  });

  it("rejects a traversing hook name during install too", async () => {
    const { base, gitDir } = await fixture();
    try {
      const outside = join(gitDir, "kit-install-traversal-target");
      const results = await installHooks(
        { "../kit-install-traversal-target": ["echo escaped"] },
        gitDir,
        base,
      );

      const attempted = results.find((result) =>
        result.hookName.includes("kit-install-traversal-target"),
      );
      assert.equal(attempted?.action, "failed");
      assert.match(attempted?.detail ?? "", /invalid hook name/i);
      assert.equal(existsSync(outside), false);
    } finally {
      await rm(base, { recursive: true, force: true });
    }
  });
});
