import { describe, it, beforeEach, afterEach } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync, mkdirSync, writeFileSync, realpathSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describeHookFloor, judgeHookFloor } from "./hook-floor.js";

const kitHook = (command: string): string =>
  ["#!/bin/sh", "# Generated by kit", "# Hook: test", `"$HOME/.kit/bin/kit" ${command}`, ""].join(
    "\n",
  );

function git(cwd: string, ...args: string[]): void {
  execFileSync("git", ["-C", cwd, ...args], { stdio: "ignore" });
}

let dirs: string[] = [];
const repo = (): string => {
  const d = realpathSync(mkdtempSync(join(tmpdir(), "kit-floor-")));
  dirs.push(d);
  execFileSync("git", ["init", "-q", d], { stdio: "ignore" });
  return d;
};

beforeEach(() => {
  dirs = [];
});
afterEach(() => {
  for (const d of dirs) rmSync(d, { recursive: true, force: true });
});

describe("hook floor locations and context gate", () => {
  it("reports a floor that resolves OUTSIDE the repo", () => {
    const r = repo();
    const elsewhere = realpathSync(mkdtempSync(join(tmpdir(), "kit-floor-other-")));
    dirs.push(elsewhere);
    mkdirSync(join(elsewhere, "hooks"));
    writeFileSync(join(elsewhere, "hooks", "pre-commit"), kitHook("security scan-staged"), {
      mode: 0o755,
    });
    git(r, "config", "core.hooksPath", join(elsewhere, "hooks"));

    const f = describeHookFloor(r);
    assert.equal(f.external, true, "a hooks dir in another tree is external");
    assert.equal(f.dir, join(elsewhere, "hooks"));
    assert.equal(f.hooksPath, join(elsewhere, "hooks"));
    assert.deepEqual(f.installed, ["secret-scan"]);

    const v = judgeHookFloor(f);
    assert.equal(v.status, "warn");
    assert.match(v.detail, /OUTSIDE/);
    assert.match(v.detail, /silently removes the gate/);
  });

  it("a repo-relative hooksPath inside the repo is NOT external (the husky/.githooks case)", () => {
    const r = repo();
    mkdirSync(join(r, ".githooks"));
    writeFileSync(join(r, ".githooks", "pre-commit"), kitHook("security scan-staged"), {
      mode: 0o755,
    });
    git(r, "config", "core.hooksPath", ".githooks");

    const f = describeHookFloor(r);
    assert.equal(f.external, false);
    assert.equal(f.exists, true);
    assert.equal(judgeHookFloor(f).status, "pass");
  });

  it("a hooksPath pointing at a deleted directory means every hook is OFF", () => {
    const r = repo();
    const gone = join(tmpdir(), "kit-floor-deleted-does-not-exist", "hooks");
    git(r, "config", "core.hooksPath", gone);

    const f = describeHookFloor(r);
    assert.equal(f.exists, false);
    assert.deepEqual(f.installed, [], "nothing can be installed in a directory that is gone");

    const v = judgeHookFloor(f);
    assert.equal(v.status, "fail");
    assert.equal(v.severity, "high");
    assert.match(v.detail, /does not exist — every git hook is OFF/);
  });

  it("context-check with no [context] block is reported as unarmed", () => {
    const r = repo();
    writeFileSync(join(r, ".git", "hooks", "pre-push"), kitHook("context check"), { mode: 0o755 });
    const f = describeHookFloor(r, undefined);
    assert.deepEqual(f.installed, ["context-check"]);
    assert.deepEqual(f.unarmed, ["context-check"]);

    const v = judgeHookFloor(f);
    assert.equal(v.status, "fail");
    assert.match(v.detail, /cannot fail/);
  });

  it("context-check with a [context] block is armed", () => {
    const r = repo();
    writeFileSync(join(r, ".git", "hooks", "pre-push"), kitHook("context check"), { mode: 0o755 });
    const f = describeHookFloor(r, { context: { github: { org: "acme" } } });
    assert.deepEqual(f.unarmed, []);
    assert.equal(judgeHookFloor(f).status, "pass");
  });
});
