/**
 * Self-healing kit wrapper for hook shells (headless bootstrap, #reach).
 *
 * Git hooks and Claude Code memory-capture hooks invoke kit, but they run in a
 * NON-LOGIN /bin/sh (containers, CI, some agent runners) whose PATH usually
 * lacks the mise shims dir AND the npm global bin (~/.npm-global/bin). A bare
 * `kit` there fails with "command not found" and the hook SILENTLY does nothing
 * — memory + audit capture never fire, which is the worst failure mode because
 * the store looks installed but records nothing.
 *
 * The fix is a tiny POSIX-sh wrapper written to ~/.kit/bin/kit on hook install.
 * It prepends the mise shims dir + the npm global bin to PATH (so any tool kit
 * shells out to resolves), then exec's the REAL kit by absolute path
 * (<node> <dist/cli.js>, resolved at write time) so kit itself always runs
 * regardless of the hook shell. Hooks reference this wrapper by absolute path.
 *
 * Honest + safe: the wrapper carries a marker line and ensureKitWrapper never
 * overwrites a ~/.kit/bin/kit that lacks it (a file the user authored). No
 * secrets are written. The generator is pure so the assembled PATH + exec line
 * are unit-testable without touching the filesystem.
 */
import { existsSync, readFileSync, writeFileSync, chmodSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";

/** Marker that identifies a kit-managed wrapper. ensureKitWrapper refuses to
 *  clobber a ~/.kit/bin/kit that does not contain it. */
export const WRAPPER_MARKER = "# kit-managed wrapper (do not edit)";

export interface WrapperSpec {
  /** Absolute path to the node binary that runs kit. */
  nodePath: string;
  /** Absolute path to kit's dist/cli.js entrypoint. */
  cliPath: string;
  /** mise shims dir, included on PATH only when mise is present. */
  miseShimsDir?: string;
  /** npm global bin (~/.npm-global/bin) — where a global `kit` install lands. */
  npmGlobalBin?: string;
}

export type WrapperAction = "written" | "updated" | "unchanged" | "unmanaged" | "skipped";

export interface EnsureWrapperResult {
  path: string;
  action: WrapperAction;
  detail: string;
}

/** Directory holding kit's managed per-user binaries. */
export function kitBinDir(home = homedir()): string {
  return join(home, ".kit", "bin");
}

/** Absolute path of the managed wrapper. */
export function kitWrapperPath(home = homedir()): string {
  return join(kitBinDir(home), "kit");
}

/**
 * Absolute path of the Windows companion shim (`kit.cmd`). On native Windows the
 * POSIX `kit` wrapper is not runnable by cmd/PowerShell (no shebang, no exec
 * bit), so we additionally emit a `.cmd` batch shim that does the same job:
 * prepend the tool dirs to PATH, then invoke the real kit via node + cli.js. #43.
 */
export function kitCmdWrapperPath(home = homedir()): string {
  return join(kitBinDir(home), "kit.cmd");
}

/**
 * The PATH dirs the wrapper prepends, in priority order. Pure: drives both the
 * generated script and the "would this resolve kit in a non-login shell?" test.
 */
export function wrapperPathDirs(spec: WrapperSpec): string[] {
  const dirs: string[] = [];
  if (spec.miseShimsDir) dirs.push(spec.miseShimsDir);
  if (spec.npmGlobalBin) dirs.push(spec.npmGlobalBin);
  return dirs;
}

/**
 * Emit the wrapper script for a resolved spec. POSIX sh (the shell git + Claude
 * Code hooks run under). Prepends tool dirs to PATH, then exec's the real kit by
 * absolute path so it runs no matter what the hook shell's PATH was.
 */
export function generateKitWrapper(spec: WrapperSpec): string {
  const dirs = wrapperPathDirs(spec);
  const pathLine = dirs.length
    ? `export PATH="${dirs.join(":")}:$PATH"`
    : "# no mise shims or npm global bin detected at install time";
  return [
    "#!/bin/sh",
    WRAPPER_MARKER,
    "# Regenerated by `kit memory install` / `kit hooks add`. Restores the tool",
    "# PATH a non-login hook shell drops, then exec's the real kit by absolute",
    "# path so capture + audit always fire. Edit kit, not this file.",
    pathLine,
    `exec "${spec.nodePath}" "${spec.cliPath}" "$@"`,
    "",
  ].join("\n");
}

/**
 * Emit the Windows `.cmd` companion shim for a resolved spec. Batch syntax: set
 * PATH for this process, then run node + cli.js forwarding all args (`%*`). The
 * marker keeps it self-describing and lets ensureKitWrapper detect its own shim.
 */
export function generateKitCmdWrapper(spec: WrapperSpec): string {
  const dirs = wrapperPathDirs(spec);
  const pathLine = dirs.length
    ? `set "PATH=${dirs.join(";")};%PATH%"`
    : "rem no mise shims or npm global bin detected at install time";
  // CRLF line endings: cmd.exe is the consumer, and a bare-LF .cmd can misparse.
  return [
    "@echo off",
    `rem ${WRAPPER_MARKER.replace(/^# /, "")}`,
    "rem Restores the tool PATH a non-login hook shell drops, then runs the real",
    "rem kit by absolute node + cli.js. Edit kit, not this file.",
    pathLine,
    `"${spec.nodePath}" "${spec.cliPath}" %*`,
    "",
  ].join("\r\n");
}

export interface EnsureWrapperOpts {
  home?: string;
  nodePath?: string;
  cliPath?: string;
  miseShimsDir?: string;
  npmGlobalBin?: string;
}

/** Default mise shims dir, included only when it actually exists on this host. */
function defaultMiseShimsDir(home: string): string | undefined {
  const shims = join(home, ".local", "share", "mise", "shims");
  return existsSync(shims) ? shims : undefined;
}

/**
 * Create or refresh ~/.kit/bin/kit. Idempotent (no write when already current),
 * 0755, and never clobbers an unmanaged file at that path. Returns what it did.
 */
export function ensureKitWrapper(opts: EnsureWrapperOpts = {}): EnsureWrapperResult {
  const home = opts.home ?? homedir();
  const path = kitWrapperPath(home);

  const cliEntry = opts.cliPath ?? (process.argv[1] ? resolve(process.argv[1]) : undefined);
  if (!cliEntry) {
    return {
      path,
      action: "skipped",
      detail: "could not resolve kit's cli.js path — wrapper not written",
    };
  }

  const spec: WrapperSpec = {
    nodePath: opts.nodePath ?? process.execPath,
    cliPath: cliEntry,
    miseShimsDir: opts.miseShimsDir ?? defaultMiseShimsDir(home),
    npmGlobalBin: opts.npmGlobalBin ?? join(home, ".npm-global", "bin"),
  };
  const desired = generateKitWrapper(spec);

  if (existsSync(path)) {
    const current = readFileSync(path, "utf-8");
    if (!current.includes(WRAPPER_MARKER)) {
      return {
        path,
        action: "unmanaged",
        detail: `${path} exists but is not kit-managed — left untouched`,
      };
    }
    if (current === desired) {
      // Even when the POSIX wrapper is current, make sure the Windows companion
      // shim exists (e.g. a wrapper written by an older kit predates it).
      ensureCmdShim(home, spec);
      return { path, action: "unchanged", detail: "already up to date" };
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, desired, "utf-8");
    chmodSync(path, 0o755);
    ensureCmdShim(home, spec);
    return { path, action: "updated", detail: "refreshed node/cli/PATH" };
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, desired, "utf-8");
  chmodSync(path, 0o755);
  ensureCmdShim(home, spec);
  return { path, action: "written", detail: "created self-healing wrapper" };
}

/**
 * On native Windows, write the `kit.cmd` companion next to the POSIX wrapper so
 * cmd/PowerShell can actually run it (the POSIX `kit` file has no shebang/exec
 * bit there). No-op on POSIX, where the sh wrapper is the only artifact. #43.
 */
function ensureCmdShim(home: string, spec: WrapperSpec): void {
  if (process.platform !== "win32") return;
  const cmdPath = kitCmdWrapperPath(home);
  const desired = generateKitCmdWrapper(spec);
  if (existsSync(cmdPath)) {
    const current = readFileSync(cmdPath, "utf-8");
    if (!current.includes(WRAPPER_MARKER) || current === desired) return;
  }
  mkdirSync(dirname(cmdPath), { recursive: true });
  writeFileSync(cmdPath, desired, "utf-8");
}
