import { createServer } from "node:net";
import { spawn, type ChildProcess } from "node:child_process";
import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, extname, join, relative, resolve } from "node:path";
import { detectStack, type DetectedStack } from "./stack-detector.js";

export type MonkeySeverity = "critical" | "high" | "medium" | "low";
export type MonkeyArea = "runner" | "ux" | "a11y" | "i18n" | "money" | "authz" | "security";

export interface MonkeyRole {
  id: "public" | "customer" | "staff" | "owner" | "superadmin";
  label: string;
  description: string;
  storageStateEnv?: string;
  defaultStorageState?: string;
}

export const MONKEY_ROLES: readonly MonkeyRole[] = [
  {
    id: "public",
    label: "Public visitor",
    description: "Unauthenticated user. Must see only public routes and no private data.",
  },
  {
    id: "customer",
    label: "Customer/buyer",
    description: "Authenticated buyer. Can manage own cart, orders, receipts, and refunds.",
    storageStateEnv: "MONKEY_CUSTOMER_STATE",
    defaultStorageState: ".auth/customer.json",
  },
  {
    id: "staff",
    label: "Kiosk staff",
    description:
      "Frontline kiosk staff role. Keep it separate from owner/admin and from any kiosk device abstraction.",
    storageStateEnv: "MONKEY_STAFF_STATE",
    defaultStorageState: ".auth/staff.json",
  },
  {
    id: "owner",
    label: "Owner/admin",
    description: "Business owner or tenant admin. Can manage catalog, staff, payouts, and reports.",
    storageStateEnv: "MONKEY_OWNER_STATE",
    defaultStorageState: ".auth/owner.json",
  },
  {
    id: "superadmin",
    label: "Superadmin/support",
    description: "Platform support role. Must be audited and isolated from tenant-scoped mutation.",
    storageStateEnv: "MONKEY_SUPERADMIN_STATE",
    defaultStorageState: ".auth/superadmin.json",
  },
];

export interface MonkeyFinding {
  severity: MonkeySeverity;
  area: MonkeyArea;
  title: string;
  role: string;
  route: string;
  repro: string;
  file?: string;
  fix: string;
}

export interface MonkeyPlanCheck {
  name: string;
  status: "pass" | "warn" | "fail" | "skip";
  detail: string;
  file?: string;
}

export interface MonkeyTestPlan {
  cwd: string;
  stack: DetectedStack;
  packageManager: "npm" | "pnpm" | "yarn" | "bun" | "unknown";
  commands: {
    dev?: string;
    build?: string;
    test?: string;
    seed?: string;
  };
  playwright: {
    dependency: boolean;
    config: boolean;
    monkeyConfig: boolean;
  };
  env: {
    kitSecrets: boolean;
    envExample: boolean;
    envCommand?: string;
  };
  money: {
    providers: string[];
    sandboxOnly: boolean;
  };
  harness: {
    files: string[];
    missing: string[];
  };
  roles: readonly MonkeyRole[];
  checks: MonkeyPlanCheck[];
  findings: MonkeyFinding[];
  nextSteps: string[];
}

export interface MonkeyPlanOptions {
  envCommand?: string;
}

export interface HarnessWrite {
  path: string;
  action: "created" | "updated" | "unchanged" | "skipped";
  reason?: string;
}

export interface HarnessWriteResult {
  ok: boolean;
  writes: HarnessWrite[];
}

export interface MonkeyRunOptions {
  baseUrl?: string;
  startCommand?: string;
  seedCommand?: string;
  testCommand?: string;
  envCommand?: string;
  linkDepth?: number;
  skipSeed?: boolean;
  skipBrowser?: boolean;
  skipSecurity?: boolean;
  expectedReason?: string;
  timeoutMs?: number;
}

export interface MonkeyRunResult {
  ok: boolean;
  plan: MonkeyTestPlan;
  port?: number;
  baseUrl?: string;
  findings: MonkeyFinding[];
  steps: { name: string; status: "pass" | "fail" | "skip"; detail: string }[];
}

interface PackageJson {
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  packageManager?: string;
  prisma?: { seed?: string };
}

const MANAGED = "Generated by kit monkey-test";
const HARNESS_FILES = [
  "playwright.monkey.config.ts",
  "tests/monkey/monkey.spec.ts",
  "tests/monkey/README.md",
  "tests/monkey/security-checklist.md",
  ".kit/monkey-test/role-matrix.json",
  ".kit/monkey-test/expected-findings.example.json",
] as const;

const SOURCE_EXTS = new Set([
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".sql",
  ".py",
  ".rb",
  ".go",
  ".rs",
  ".php",
  ".java",
  ".kt",
  ".cs",
  ".html",
  ".toml",
  ".json",
  ".yaml",
  ".yml",
  ".md",
]);

const SKIP_DIRS = new Set([
  ".git",
  "node_modules",
  "dist",
  "build",
  "out",
  ".next",
  ".nuxt",
  "coverage",
  ".cache",
  "vendor",
  "tmp",
  "test-results",
  "playwright-report",
]);

async function readJson<T>(path: string): Promise<T | null> {
  try {
    return JSON.parse(await readFile(path, "utf-8")) as T;
  } catch {
    return null;
  }
}

async function readText(path: string): Promise<string> {
  try {
    return await readFile(path, "utf-8");
  } catch {
    return "";
  }
}

function allDeps(pkg: PackageJson | null): Record<string, string> {
  return { ...(pkg?.dependencies ?? {}), ...(pkg?.devDependencies ?? {}) };
}

function detectPackageManager(
  pkg: PackageJson | null,
  cwd: string,
): MonkeyTestPlan["packageManager"] {
  const declared = pkg?.packageManager ?? "";
  if (declared.startsWith("pnpm")) return "pnpm";
  if (declared.startsWith("yarn")) return "yarn";
  if (declared.startsWith("bun")) return "bun";
  if (existsSync(join(cwd, "pnpm-lock.yaml"))) return "pnpm";
  if (existsSync(join(cwd, "yarn.lock"))) return "yarn";
  if (existsSync(join(cwd, "bun.lock")) || existsSync(join(cwd, "bun.lockb"))) return "bun";
  if (pkg) return "npm";
  return "unknown";
}

function scriptCommand(
  packageManager: MonkeyTestPlan["packageManager"],
  name: string,
): string | undefined {
  if (packageManager === "unknown") return undefined;
  if (packageManager === "npm") return `npm run ${name}`;
  if (packageManager === "pnpm") return `pnpm run ${name}`;
  if (packageManager === "yarn") return `yarn ${name}`;
  return `bun run ${name}`;
}

function pickScript(
  pkg: PackageJson | null,
  packageManager: MonkeyTestPlan["packageManager"],
  candidates: RegExp[],
): string | undefined {
  const scripts = pkg?.scripts ?? {};
  for (const candidate of candidates) {
    for (const [name, command] of Object.entries(scripts)) {
      if (candidate.test(name) || candidate.test(command))
        return scriptCommand(packageManager, name);
    }
  }
  return undefined;
}

function detectCommands(
  pkg: PackageJson | null,
  packageManager: MonkeyTestPlan["packageManager"],
): MonkeyTestPlan["commands"] {
  const scripts = pkg?.scripts ?? {};
  return {
    dev:
      (scripts.dev ? scriptCommand(packageManager, "dev") : undefined) ??
      (scripts.start ? scriptCommand(packageManager, "start") : undefined) ??
      (scripts.preview ? scriptCommand(packageManager, "preview") : undefined) ??
      pickScript(pkg, packageManager, [/^serve$/, /^web$/, /^app$/]),
    build: scripts.build ? scriptCommand(packageManager, "build") : undefined,
    test:
      pickScript(pkg, packageManager, [/playwright/i, /e2e/i, /^test$/]) ??
      defaultPlaywrightCommand(packageManager),
    seed:
      pickScript(pkg, packageManager, [/seed/i, /db:reset/i, /db:setup/i]) ??
      (pkg?.prisma?.seed ? pkg.prisma.seed : undefined),
  };
}

function defaultPlaywrightCommand(
  packageManager: MonkeyTestPlan["packageManager"],
): string | undefined {
  if (packageManager === "npm")
    return "npx --no-install playwright test -c playwright.monkey.config.ts";
  if (packageManager === "pnpm") return "pnpm exec playwright test -c playwright.monkey.config.ts";
  if (packageManager === "yarn") return "yarn playwright test -c playwright.monkey.config.ts";
  if (packageManager === "bun") return "bunx playwright test -c playwright.monkey.config.ts";
  return undefined;
}

function paymentProviders(deps: Record<string, string>, sourceText: string): string[] {
  const providers = new Set<string>();
  const depNames = Object.keys(deps).join("\n");
  if (/\bstripe\b|@stripe\//i.test(depNames)) providers.add("stripe");
  if (/\badyen\b/i.test(depNames)) providers.add("adyen");
  if (/\bpaypal\b|braintree/i.test(depNames)) providers.add("paypal");
  if (/\bsquare\b/i.test(depNames)) providers.add("square");
  if (
    /from\s+["']stripe["']|require\(["']stripe["']\)|@stripe\/|new\s+Stripe\(|loadStripe\(|js\.stripe\.com|stripe\.webhooks\.constructEvent/i.test(
      sourceText,
    )
  )
    providers.add("stripe");
  if (
    /from\s+["']@adyen\/|require\(["']@adyen\/|(?:new\s+)?AdyenCheckout\(|checkoutshopper-[a-z-]+\.adyen\.com/i.test(
      sourceText,
    )
  )
    providers.add("adyen");
  if (
    /paypal\.com\/sdk\/js|from\s+["']@paypal\/|require\(["']@paypal\/|braintree\.(client|dropin|hostedFields)|new\s+Braintree/i.test(
      sourceText,
    )
  )
    providers.add("paypal");
  if (
    /connect\.squareupsandbox\.com|connect\.squareup\.com|from\s+["']@square\/|require\(["']@square\/|new\s+Square/i.test(
      sourceText,
    )
  )
    providers.add("square");
  return [...providers].sort();
}

function isRuntimeSourcePath(path: string): boolean {
  if (
    path.startsWith("docs/") ||
    path.startsWith("skills/") ||
    path.startsWith("contracts/") ||
    path.startsWith(".kit/") ||
    path.includes("/tests/") ||
    path.includes("/__tests__/") ||
    path.includes("/fixtures/") ||
    path.includes("/mocks/")
  )
    return false;
  if (/(^|\/)(test|tests|fixtures|mocks)\//i.test(path)) return false;
  if (/\.(test|spec|fixture|mock|snapshot)\.[cm]?[jt]sx?$/i.test(path)) return false;
  if (path.endsWith(".md")) return false;
  return true;
}

async function candidateFiles(cwd: string, maxFiles = 500): Promise<string[]> {
  const out: string[] = [];
  const stack: string[] = [cwd];
  while (stack.length > 0 && out.length < maxFiles) {
    const dir = stack.pop()!;
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      if (entry.isDirectory()) {
        if (!SKIP_DIRS.has(entry.name)) stack.push(join(dir, entry.name));
        continue;
      }
      if (!entry.isFile()) continue;
      const ext = extname(entry.name).toLowerCase();
      if (!SOURCE_EXTS.has(ext)) continue;
      out.push(join(dir, entry.name));
      if (out.length >= maxFiles) break;
    }
  }
  return out;
}

async function scanSources(cwd: string): Promise<{
  text: string;
  files: Record<string, string>;
  runtimeText: string;
  runtimeFiles: Record<string, string>;
}> {
  const files: Record<string, string> = {};
  const runtimeFiles: Record<string, string> = {};
  const chunks: string[] = [];
  const runtimeChunks: string[] = [];
  for (const file of await candidateFiles(cwd)) {
    let info;
    try {
      info = await stat(file);
    } catch {
      continue;
    }
    if (info.size > 512 * 1024) continue;
    const text = await readText(file);
    const rel = relative(cwd, file).split("\\").join("/");
    files[rel] = text;
    chunks.push(`\n--- ${rel} ---\n${text}`);
    if (isRuntimeSourcePath(rel)) {
      runtimeFiles[rel] = text;
      runtimeChunks.push(`\n--- ${rel} ---\n${text}`);
    }
  }
  return {
    text: chunks.join("\n"),
    files,
    runtimeText: runtimeChunks.join("\n"),
    runtimeFiles,
  };
}

function firstFileMatching(files: Record<string, string>, pattern: RegExp): string | undefined {
  return Object.entries(files).find(([, text]) => pattern.test(text))?.[0];
}

function hasAny(text: string, patterns: RegExp[]): boolean {
  return patterns.some((p) => p.test(text));
}

function finding(
  input: Omit<MonkeyFinding, "role" | "route"> & Partial<Pick<MonkeyFinding, "role" | "route">>,
): MonkeyFinding {
  return {
    ...input,
    role: input.role ?? "all",
    route: input.route ?? "*",
  };
}

export async function securityFindings(cwd: string): Promise<MonkeyFinding[]> {
  const pkg = await readJson<PackageJson>(join(cwd, "package.json"));
  const deps = allDeps(pkg);
  const scan = await scanSources(cwd);
  const sourceText = scan.runtimeText;
  const providers = paymentProviders(deps, sourceText);
  const usesSupabase =
    "supabase" in deps ||
    "@supabase/supabase-js" in deps ||
    existsSync(join(cwd, "supabase", "config.toml")) ||
    /supabase/i.test(sourceText);
  const findings: MonkeyFinding[] = [];
  const liveSecretFile = firstFileMatching(
    scan.runtimeFiles,
    /\b(?:sk|pk|rk)_live_[A-Za-z0-9]{16,}/,
  );
  if (liveSecretFile) {
    findings.push(
      finding({
        severity: "critical",
        area: "security",
        title: "Committed live payment key pattern",
        file: liveSecretFile,
        repro: `rg "(sk|pk|rk)_live_" ${liveSecretFile}`,
        fix: "Remove the live key, rotate it at the provider, and keep only placeholders in committed files.",
      }),
    );
  }

  for (const [key, value] of Object.entries(process.env)) {
    if (!/STRIPE|PAYMENT|CONNECT/i.test(key)) continue;
    if (/^(sk|pk|rk)_live_/.test(value ?? "")) {
      findings.push(
        finding({
          severity: "critical",
          area: "money",
          title: `Live payment credential in runtime env (${key})`,
          repro: `env | rg "^${key}="`,
          fix: "Run monkey-test with sandbox/test credentials only; never drive release gates against live payment rails.",
        }),
      );
    }
  }

  if (usesSupabase) {
    const hasRls =
      /enable\s+row\s+level\s+security|alter\s+table[\s\S]{0,80}enable\s+row\s+level\s+security/i.test(
        sourceText,
      );
    const hasPolicy = /create\s+policy|auth\.uid\(\)|current_setting\(['"]request\.jwt/i.test(
      sourceText,
    );
    if (!hasRls || !hasPolicy) {
      findings.push(
        finding({
          severity: "high",
          area: "authz",
          title: "Supabase detected without obvious RLS policy coverage",
          file: firstFileMatching(scan.runtimeFiles, /supabase|create\s+table|from\(['"]/i),
          repro: 'rg -n "enable row level security|create policy|auth.uid" supabase src',
          fix: "Add RLS policies for tenant/customer/staff/owner/support paths and cover them with role-based tests.",
        }),
      );
    }
    const hasRpc = /create\s+(or\s+replace\s+)?function|\brpc\(/i.test(sourceText);
    const rpcAuthz = /auth\.uid\(\)|jwt|current_setting\(['"]request\.jwt|security\s+invoker/i.test(
      sourceText,
    );
    if (hasRpc && !rpcAuthz) {
      findings.push(
        finding({
          severity: "high",
          area: "authz",
          title: "RPC/function path lacks obvious caller authorization",
          file: firstFileMatching(
            scan.runtimeFiles,
            /create\s+(or\s+replace\s+)?function|\brpc\(/i,
          ),
          repro: 'rg -n "create function|rpc\\(" supabase src',
          fix: "Assert caller identity and tenant scope inside every RPC, then add cross-role denial tests.",
        }),
      );
    }
    const publicBucket = firstFileMatching(
      scan.runtimeFiles,
      /public\s*[:=]\s*true|createBucket\([^)]*public/i,
    );
    if (publicBucket) {
      findings.push(
        finding({
          severity: "high",
          area: "security",
          title: "Public storage bucket declaration",
          file: publicBucket,
          repro: `rg -n "public.*true|createBucket" ${publicBucket}`,
          fix: "Default buckets to private; expose signed URLs or explicit public assets only.",
        }),
      );
    }
  }

  const tenantMarkers = /tenant_id|organization_id|organisation_id|org_id|account_id|workspace_id/i;
  if (providers.length > 0 && !tenantMarkers.test(sourceText)) {
    findings.push(
      finding({
        severity: "high",
        area: "authz",
        title: "Money app lacks obvious tenant/org isolation markers",
        repro: 'rg -n "tenant_id|organization_id|org_id|account_id|workspace_id" src db supabase',
        fix: "Thread tenant identity through auth, queries, mutations, payment objects, and webhook handlers.",
      }),
    );
  }

  if (providers.length > 0) {
    const webhookSignature = hasAny(sourceText, [
      /constructEvent|webhooks?\.construct|webhook.*signature|svix.*verify|x-.*signature/i,
      /STRIPE_WEBHOOK_SECRET|PAYPAL_WEBHOOK_ID|ADYEN_HMAC/i,
    ]);
    if (!webhookSignature) {
      findings.push(
        finding({
          severity: "critical",
          area: "money",
          title: "Payment provider detected without webhook signature verification",
          repro:
            'rg -n "constructEvent|webhook.*signature|STRIPE_WEBHOOK_SECRET|svix" src app pages api',
          fix: "Verify every webhook with the provider signature before parsing or mutating state.",
        }),
      );
    }
    const idempotency = /idempotenc|event\.id|webhook_events|processed_events|dedupe/i.test(
      sourceText,
    );
    if (!idempotency) {
      findings.push(
        finding({
          severity: "high",
          area: "money",
          title: "Payment webhook path lacks obvious idempotency ledger",
          repro:
            'rg -n "idempotenc|event.id|webhook_events|processed_events|dedupe" src db supabase',
          fix: "Persist provider event IDs and make webhook side effects idempotent before release.",
        }),
      );
    }
    if (!/refund/i.test(sourceText)) {
      findings.push(
        finding({
          severity: "medium",
          area: "money",
          title: "Refund path not found",
          repro: 'rg -n "refund" src app pages api db supabase',
          fix: "Add a tested refund/cancel path with authorization, receipt update, and immutable journal entry.",
        }),
      );
    }
    if (!/receipt/i.test(sourceText)) {
      findings.push(
        finding({
          severity: "medium",
          area: "money",
          title: "Receipt path not found",
          repro: 'rg -n "receipt" src app pages api db supabase',
          fix: "Generate customer-visible receipts from settled test-mode payment state.",
        }),
      );
    }
    if (!/ledger|journal|append.only|immutable/i.test(sourceText)) {
      findings.push(
        finding({
          severity: "high",
          area: "money",
          title: "Immutable money journal not found",
          repro: 'rg -n "ledger|journal|append|immutable" src app pages api db supabase',
          fix: "Record append-only payment/refund/journal events and forbid destructive edits.",
        }),
      );
    }
  }

  const webApp = /next|remix|svelte|astro|react|vue|express/i.test(Object.keys(deps).join("\n"));
  if (webApp && !/Content-Security-Policy|contentSecurityPolicy|headers\s*\(/i.test(sourceText)) {
    findings.push(
      finding({
        severity: "medium",
        area: "security",
        title: "CSP/header policy not found",
        repro: 'rg -n "Content-Security-Policy|contentSecurityPolicy|headers\\(" .',
        fix: "Add CSP and security headers for app and payment routes; include the sandbox payment domains needed by tests.",
      }),
    );
  }

  return prioritizeFindings(findings);
}

export function prioritizeFindings(findings: MonkeyFinding[]): MonkeyFinding[] {
  const weight: Record<MonkeySeverity, number> = { critical: 0, high: 1, medium: 2, low: 3 };
  return [...findings].sort(
    (a, b) =>
      weight[a.severity] - weight[b.severity] ||
      a.area.localeCompare(b.area) ||
      a.title.localeCompare(b.title),
  );
}

export async function buildMonkeyTestPlan(
  cwd: string = process.cwd(),
  options: MonkeyPlanOptions = {},
): Promise<MonkeyTestPlan> {
  const root = resolve(cwd);
  const pkg = await readJson<PackageJson>(join(root, "package.json"));
  const deps = allDeps(pkg);
  const stack = await detectStack(root);
  const packageManager = detectPackageManager(pkg, root);
  const commands = detectCommands(pkg, packageManager);
  const scan = await scanSources(root);
  const providers = paymentProviders(deps, scan.runtimeText);
  const playwright = {
    dependency: "@playwright/test" in deps || "playwright" in deps,
    config:
      existsSync(join(root, "playwright.config.ts")) ||
      existsSync(join(root, "playwright.config.js")) ||
      existsSync(join(root, "playwright.config.mjs")),
    monkeyConfig: existsSync(join(root, "playwright.monkey.config.ts")),
  };
  const env = {
    kitSecrets: /\[secrets\]/.test(await readText(join(root, ".kit.toml"))),
    envExample:
      existsSync(join(root, ".env.example")) ||
      existsSync(join(root, ".env.template")) ||
      existsSync(join(root, ".env.sample")),
    envCommand: options.envCommand,
  };
  const harnessMissing = HARNESS_FILES.filter((file) => !existsSync(join(root, file)));
  const findings = await securityFindings(root);
  const checks: MonkeyPlanCheck[] = [
    {
      name: "stack",
      status: stack.language === "unknown" ? "warn" : "pass",
      detail: `${stack.language}${stack.framework ? `/${stack.framework}` : ""} (${Math.round(
        stack.confidence * 100,
      )}% confidence)`,
    },
    {
      name: "test runner",
      status: playwright.dependency ? "pass" : "fail",
      detail: playwright.dependency
        ? "Playwright dependency found"
        : "No @playwright/test or playwright dependency found",
      file: "package.json",
    },
    {
      name: "dev server",
      status: commands.dev ? "pass" : "fail",
      detail:
        commands.dev ?? "No dev/start/preview script detected; pass --start-command or --base-url",
      file: "package.json",
    },
    {
      name: "seed",
      status: commands.seed ? "pass" : "warn",
      detail:
        commands.seed ?? "No seed script detected; use --seed-command or --skip-seed with a reason",
      file: "package.json",
    },
    {
      name: "env",
      status: env.envCommand || env.kitSecrets || env.envExample ? "pass" : "warn",
      detail: env.envCommand
        ? `temporary env from ${env.envCommand}`
        : env.kitSecrets
          ? "kit secrets declared"
          : env.envExample
            ? "env template found"
            : "No env source detected; pass --env-command so secrets stay out of .env files",
    },
    {
      name: "money provider",
      status: providers.length > 0 ? "pass" : "warn",
      detail: providers.length > 0 ? providers.join(", ") : "No payment provider marker detected",
    },
    {
      name: "harness",
      status: harnessMissing.length === 0 ? "pass" : "warn",
      detail:
        harnessMissing.length === 0
          ? "monkey-test harness present"
          : `${harnessMissing.length} harness file(s) missing; run kit monkey-test init`,
    },
  ];
  const nextSteps: string[] = [];
  if (harnessMissing.length > 0) nextSteps.push("kit monkey-test init");
  if (!playwright.dependency)
    nextSteps.push("kit triage npm @playwright/test before installing it");
  if (!commands.dev) nextSteps.push("kit monkey-test run --start-command '<dev server command>'");
  if (!commands.seed)
    nextSteps.push("kit monkey-test run --seed-command '<idempotent seed command>'");
  if (!env.envCommand && !env.kitSecrets) {
    nextSteps.push("provide --env-command '<provider cli that prints KEY=VALUE lines>'");
  }
  if (providers.length > 0) {
    nextSteps.push("set MONKEY_MONEY_ROUTE, MONKEY_ADD_TO_CART, and MONKEY_CHECKOUT");
  }

  return {
    cwd: root,
    stack,
    packageManager,
    commands,
    playwright,
    env,
    money: {
      providers,
      sandboxOnly: findings.every((f) => !/live payment|payment credential/i.test(f.title)),
    },
    harness: {
      files: [...HARNESS_FILES],
      missing: harnessMissing,
    },
    roles: MONKEY_ROLES,
    checks,
    findings,
    nextSteps,
  };
}

function generatedHeader(path: string): string {
  return `// ${MANAGED}. Edit source in kit or re-run \`kit monkey-test init --force\`.\n// File: ${path}\n\n`;
}

function roleMatrixJson(): string {
  return (
    JSON.stringify(
      {
        generatedBy: "kit monkey-test",
        roles: MONKEY_ROLES,
        note: "The staff role is kiosk staff. Keep it separate from owner/admin and from kiosk device state.",
      },
      null,
      2,
    ) + "\n"
  );
}

function expectedFindingsJson(): string {
  return (
    JSON.stringify(
      [
        {
          area: "ux",
          role: "public",
          route: "/maintenance",
          title: "Known maintenance banner",
          reason: "Launch-day maintenance banner is approved by product until 2026-09-15.",
        },
      ],
      null,
      2,
    ) + "\n"
  );
}

function playwrightConfig(): string {
  return `${generatedHeader("playwright.monkey.config.ts")}import { defineConfig, devices } from "@playwright/test";

const rawPort = Number(process.env.KIT_MONKEY_PORT ?? process.env.PORT ?? "0");
const port = Number.isFinite(rawPort) && rawPort > 0 ? rawPort : 0;
const baseURL =
  process.env.MONKEY_BASE_URL ?? (port > 0 ? \`http://127.0.0.1:\${port}\` : "http://127.0.0.1:4173");

export default defineConfig({
  testDir: "./tests/monkey",
  timeout: 60_000,
  expect: { timeout: 10_000 },
  fullyParallel: false,
  reporter: [
    ["list"],
    ["json", { outputFile: ".kit/monkey-test/playwright-report.json" }],
  ],
  use: {
    baseURL,
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
  },
  projects: [
    {
      name: "desktop-chromium",
      use: { ...devices["Desktop Chrome"], viewport: { width: 1440, height: 900 } },
    },
    {
      name: "mobile-chrome",
      use: { ...devices["Pixel 7"] },
    },
  ],
});
`;
}

function monkeySpec(): string {
  return `${generatedHeader("tests/monkey/monkey.spec.ts")}import { existsSync, readFileSync } from "node:fs";
import { test, expect, type Page } from "@playwright/test";

type Severity = "critical" | "high" | "medium" | "low";
type Finding = {
  severity: Severity;
  area: "runner" | "ux" | "a11y" | "i18n" | "money" | "authz" | "security";
  title: string;
  role: string;
  route: string;
  repro: string;
  file?: string;
  fix: string;
};

const roles = [
  { id: "public", label: "Public visitor" },
  { id: "customer", label: "Customer/buyer", env: "MONKEY_CUSTOMER_STATE", fallback: ".auth/customer.json" },
  { id: "staff", label: "Kiosk staff", env: "MONKEY_STAFF_STATE", fallback: ".auth/staff.json" },
  { id: "owner", label: "Owner/admin", env: "MONKEY_OWNER_STATE", fallback: ".auth/owner.json" },
  { id: "superadmin", label: "Superadmin/support", env: "MONKEY_SUPERADMIN_STATE", fallback: ".auth/superadmin.json" },
] as const;

const severityRank: Record<Severity, number> = { critical: 0, high: 1, medium: 2, low: 3 };

function envList(name: string, fallback: string[]): string[] {
  const raw = process.env[name];
  if (!raw) return fallback;
  return raw.split(",").map((x) => x.trim()).filter(Boolean);
}

function envInt(name: string, fallback: number): number {
  const n = Number(process.env[name]);
  return Number.isFinite(n) && n >= 0 ? n : fallback;
}

function storageState(role: (typeof roles)[number]): string | undefined {
  if (!("env" in role)) return undefined;
  const path = process.env[role.env] ?? role.fallback;
  return existsSync(path) ? path : undefined;
}

function loadExpected(): (Partial<Finding> & { reason?: string })[] {
  const path = process.env.MONKEY_EXPECTED_FINDINGS;
  if (!path) return [];
  const parsed = JSON.parse(readFileSync(path, "utf-8")) as (Partial<Finding> & { reason?: string })[];
  const bad = parsed.filter((item) => !item.reason || item.reason.trim().length < 8);
  if (bad.length > 0) {
    throw new Error("MONKEY_EXPECTED_FINDINGS entries must include a specific reason.");
  }
  return parsed;
}

function matchesExpected(finding: Finding, expected: Partial<Finding>): boolean {
  for (const key of ["severity", "area", "title", "role", "route", "file"] as const) {
    if (expected[key] && expected[key] !== finding[key]) return false;
  }
  return true;
}

function unexpected(findings: Finding[]): Finding[] {
  const expected = loadExpected();
  return findings.filter((finding) => !expected.some((item) => matchesExpected(finding, item)));
}

function summarize(findings: Finding[]): string {
  return findings
    .sort((a, b) => severityRank[a.severity] - severityRank[b.severity])
    .map(
      (f) =>
        \`[\${f.severity}] \${f.area} \${f.role} \${f.route}: \${f.title}\\n  repro: \${f.repro}\\n  fix: \${f.fix}\${f.file ? \`\\n  file: \${f.file}\` : ""}\`,
    )
    .join("\\n");
}

async function collectLinks(page: Page, depth: number): Promise<string[]> {
  if (depth <= 0) return [];
  return await page.locator("a[href]").evaluateAll((nodes) => {
    const origin = location.origin;
    return Array.from(nodes)
      .map((node) => (node as HTMLAnchorElement).href)
      .filter((href) => href.startsWith(origin))
      .map((href) => new URL(href).pathname + new URL(href).search);
  });
}

async function inspectPage(page: Page, role: string, route: string): Promise<Finding[]> {
  const findings: Finding[] = [];
  const controls = page.locator("button,input,select,textarea,a[href],[role='button'],[role='link']");
  const controlCount = await controls.count().catch(() => 0);
  const limit = envInt("MONKEY_CONTROL_BLOAT_LIMIT", 80);
  if (controlCount > limit) {
    findings.push({
      severity: "medium",
      area: "ux",
      title: \`Control bloat: \${controlCount} controls exceed limit \${limit}\`,
      role,
      route,
      repro: \`MONKEY_CONTROL_BLOAT_LIMIT=\${limit} npx playwright test -c playwright.monkey.config.ts\`,
      fix: "Split the route into task-focused surfaces, hide advanced controls behind menus, or tighten role permissions.",
    });
  }

  const unlabeled = await controls.evaluateAll((nodes) =>
    nodes
      .filter((node) => {
        const el = node as HTMLElement;
        const text = (el.innerText || el.getAttribute("value") || "").trim();
        return !text && !el.getAttribute("aria-label") && !el.getAttribute("title");
      })
      .slice(0, 5)
      .map((node) => (node as HTMLElement).outerHTML.slice(0, 160)),
  );
  for (const html of unlabeled) {
    findings.push({
      severity: "medium",
      area: "a11y",
      title: "Unlabeled interactive control",
      role,
      route,
      repro: html,
      fix: "Add visible text or an aria-label/title that describes the control action.",
    });
  }

  const offscreen = await page
    .locator("a[href],button,input,select,textarea,[tabindex]:not([tabindex='-1'])")
    .evaluateAll((nodes) =>
      nodes
        .filter((node) => {
          const el = node as HTMLElement;
          const box = el.getBoundingClientRect();
          const style = getComputedStyle(el);
          if (style.display === "none" || style.visibility === "hidden") return false;
          return box.right < 0 || box.bottom < 0 || box.left > innerWidth || box.top > innerHeight;
        })
        .slice(0, 5)
        .map((node) => (node as HTMLElement).outerHTML.slice(0, 160)),
    );
  for (const html of offscreen) {
    findings.push({
      severity: "high",
      area: "a11y",
      title: "Focusable control is offscreen",
      role,
      route,
      repro: html,
      fix: "Remove it from tab order while hidden, or keep the focused element inside the viewport.",
    });
  }

  const body = await page.locator("body").innerText({ timeout: 5_000 }).catch(() => "");
  const textChecks: [RegExp, Severity, Finding["area"], string, string][] = [
    [/translation missing|missing translation|i18n missing|__MSG_/i, "medium", "i18n", "Missing translation marker", "Add the missing locale key or remove the placeholder."],
    [/\\bundefined\\b|\\bnull\\b|NaN|\\[object Object\\]/i, "high", "ux", "Fatal UI copy placeholder", "Render a real empty/error state instead of leaking runtime placeholders."],
    [/lorem ipsum|todo:|coming soon/i, "medium", "ux", "Unfinished UI copy", "Replace placeholder copy or mark the route expected with a release owner reason."],
  ];
  for (const [pattern, severity, area, title, fix] of textChecks) {
    if (pattern.test(body)) {
      findings.push({ severity, area, title, role, route, repro: pattern.source, fix });
    }
  }

  const loading = await page.getByText(/loading|laddar|spinner/i).count().catch(() => 0);
  if (loading > 0) {
    findings.push({
      severity: "medium",
      area: "ux",
      title: "Loading state still visible after page settled",
      role,
      route,
      repro: "page.getByText(/loading|laddar|spinner/i)",
      fix: "Resolve the underlying request, add timeout/error copy, or hide completed loading indicators.",
    });
  }

  const emptyOrError = /\\b(no .*found|no results|empty|error|failed)\\b/i.test(body);
  if (emptyOrError && controlCount === 0) {
    findings.push({
      severity: "medium",
      area: "ux",
      title: "Empty/error state has no actionable control",
      role,
      route,
      repro: "Route contains empty/error copy and zero controls",
      fix: "Add a clear recovery action appropriate for the role.",
    });
  }
  return findings;
}

async function paymentShellSeen(page: Page): Promise<boolean> {
  await page.waitForLoadState("domcontentloaded").catch(() => undefined);
  if (/checkout|payment|billing|stripe|paypal|adyen/i.test(page.url())) return true;
  for (const frame of page.frames()) {
    if (/stripe|paypal|adyen|checkout|payment/i.test(frame.url())) return true;
  }
  const body = await page.locator("body").innerText({ timeout: 3_000 }).catch(() => "");
  return /payment|card|checkout|billing|total/i.test(body);
}

for (const role of roles) {
  test.describe(\`\${role.id}: \${role.label}\`, () => {
    const state = storageState(role);
    if (state) test.use({ storageState: state });

    test("route crawl", async ({ page }, testInfo) => {
      const findings: Finding[] = [];
      if (role.id !== "public" && !state) {
        findings.push({
          severity: "critical",
          area: "authz",
          title: \`Missing auth state for \${role.label}\`,
          role: role.id,
          route: "*",
          repro: \`Set \${"env" in role ? role.env : "MONKEY_AUTH_STATE"} or create \${"fallback" in role ? role.fallback : ".auth/user.json"}\`,
          fix: "Create deterministic storageState fixtures during idempotent seed/login setup.",
        });
      }

      const responses: Finding[] = [];
      const consoleErrors: Finding[] = [];
      page.on("response", (response) => {
        const status = response.status();
        if (status >= 400) {
          responses.push({
            severity: status >= 500 ? "critical" : "high",
            area: "ux",
            title: \`HTTP \${status}\`,
            role: role.id,
            route: response.url(),
            repro: response.url(),
            fix: "Fix the failing request or block the route from this role intentionally.",
          });
        }
      });
      page.on("console", (message) => {
        if (message.type() === "error") {
          consoleErrors.push({
            severity: "high",
            area: "ux",
            title: "Console error",
            role: role.id,
            route: page.url(),
            repro: message.text(),
            fix: "Fix browser console errors; hydration/runtime errors are release blockers.",
          });
        }
      });
      page.on("pageerror", (error) => {
        consoleErrors.push({
          severity: "critical",
          area: "ux",
          title: "Page error",
          role: role.id,
          route: page.url(),
          repro: error.message,
          fix: "Fix uncaught browser exceptions before release.",
        });
      });

      const seeds = envList("MONKEY_ROUTES", ["/"]);
      const maxDepth = envInt("MONKEY_LINK_DEPTH", 2);
      const visited = new Set<string>();
      let frontier = seeds;
      for (let depth = 0; depth <= maxDepth; depth++) {
        const next = new Set<string>();
        for (const route of frontier) {
          if (visited.has(route)) continue;
          visited.add(route);
          await page.goto(route, { waitUntil: "domcontentloaded" }).catch((error) => {
            findings.push({
              severity: "critical",
              area: "ux",
              title: "Route navigation failed",
              role: role.id,
              route,
              repro: error.message,
              fix: "Make the route reachable for this role or remove it from MONKEY_ROUTES.",
            });
          });
          await page.waitForLoadState("networkidle", { timeout: 5_000 }).catch(() => undefined);
          findings.push(...(await inspectPage(page, role.id, route)));
          for (const link of await collectLinks(page, maxDepth - depth)) next.add(link);
        }
        frontier = [...next];
      }

      findings.push(...responses, ...consoleErrors);
      const open = unexpected(findings);
      await testInfo.attach("monkey-findings.json", {
        body: JSON.stringify(open, null, 2),
        contentType: "application/json",
      });
      expect(open, summarize(open)).toEqual([]);
    });
  });
}

test("money flow opens sandbox payment shell", async ({ page }) => {
  const liveKeys = Object.entries(process.env)
    .filter(([key, value]) => /STRIPE|PAYMENT|CONNECT/i.test(key) && /^(sk|pk|rk)_live_/.test(value ?? ""))
    .map(([key]) => key);
  expect(liveKeys, \`Live payment env keys are not allowed in monkey-test: \${liveKeys.join(", ")}\`).toEqual([]);

  if (process.env.MONKEY_SKIP_MONEY_FLOW === "1") {
    const reason = process.env.MONKEY_EXPECTED_REASON;
    expect(reason && reason.trim().length >= 12, "MONKEY_SKIP_MONEY_FLOW requires MONKEY_EXPECTED_REASON").toBeTruthy();
    test.skip(true, reason);
  }

  const route = process.env.MONKEY_MONEY_ROUTE;
  const addToCart = process.env.MONKEY_ADD_TO_CART;
  const checkout = process.env.MONKEY_CHECKOUT;
  const missing = [
    ["MONKEY_MONEY_ROUTE", route],
    ["MONKEY_ADD_TO_CART", addToCart],
    ["MONKEY_CHECKOUT", checkout],
  ].filter(([, value]) => !value).map(([name]) => name);
  expect(
    missing,
    \`Money flow is required. Set \${missing.join(", ")} or skip with MONKEY_SKIP_MONEY_FLOW=1 plus MONKEY_EXPECTED_REASON.\`,
  ).toEqual([]);

  await page.goto(route!);
  await page.locator(addToCart!).first().click();
  await page.locator(checkout!).first().click();
  expect(await paymentShellSeen(page), "Checkout did not open a recognizable payment shell").toBe(true);

  if (process.env.MONKEY_CONFIRM_TEST_PAYMENT === "1" && process.env.MONKEY_CONFIRM_PAYMENT) {
    await page.locator(process.env.MONKEY_CONFIRM_PAYMENT).first().click();
    await expect(page.getByText(/paid|complete|receipt|confirmed|success/i)).toBeVisible({ timeout: 20_000 });
  } else {
    await page.goBack().catch(() => undefined);
  }
});
`;
}

function harnessReadme(): string {
  return `# Monkey Test

${MANAGED}.

Role-based release gate for applications that handle money. The harness crawls
desktop and mobile routes as public visitor, customer/buyer, kiosk staff,
owner/admin, and superadmin/support, then fails on broken UX, browser runtime
errors, missing auth fixtures, inaccessible controls, and an unconfigured money
flow.

Run through kit so the runner gets a free local port and a temporary env:

\`\`\`sh
kit monkey-test run \\
  --env-command 'your-vault-or-provider-cli export --format=dotenv' \\
  --seed-command 'npm run seed:test'
\`\`\`

Useful env:

- \`MONKEY_ROUTES=/,/shop,/account\`
- \`MONKEY_LINK_DEPTH=2\`
- \`MONKEY_CUSTOMER_STATE=.auth/customer.json\`
- \`MONKEY_STAFF_STATE=.auth/staff.json\`
- \`MONKEY_OWNER_STATE=.auth/owner.json\`
- \`MONKEY_SUPERADMIN_STATE=.auth/superadmin.json\`
- \`MONKEY_MONEY_ROUTE=/shop\`
- \`MONKEY_ADD_TO_CART='button:has-text("Add")'\`
- \`MONKEY_CHECKOUT='a:has-text("Checkout"),button:has-text("Checkout")'\`
- \`MONKEY_CONFIRM_TEST_PAYMENT=1\` and \`MONKEY_CONFIRM_PAYMENT=<selector>\` for sandbox confirmation.

Do not silence failures with broad skips. Use \`MONKEY_EXPECTED_FINDINGS\` with a
specific \`reason\`, or \`MONKEY_SKIP_MONEY_FLOW=1 MONKEY_EXPECTED_REASON=...\`
only when the release owner has accepted the gap.
`;
}

function securityChecklist(): string {
  return `# Monkey Test Security Checklist

${MANAGED}.

Gate these before release:

- RLS/RPC authorization covers public, customer, kiosk staff, owner/admin, and superadmin/support.
- Cross-org isolation is asserted on reads, writes, payment objects, webhooks, exports, and support tools.
- Webhook signatures are verified before parsing provider payloads.
- Webhook idempotency stores provider event IDs and makes side effects replay-safe.
- Storage buckets default private; public buckets are deliberate static-asset exceptions.
- No committed secrets or live payment keys. Runtime env for this gate uses sandbox/test keys only.
- CSP and security headers cover app routes plus sandbox payment domains.
- Stripe/Connect, PayPal, Adyen, or other money rails run in sandbox/test mode only.
- Refunds, receipts, and payout/journal events are append-only and immutable after settlement.
`;
}

function harnessFiles(): Record<string, string> {
  return {
    "playwright.monkey.config.ts": playwrightConfig(),
    "tests/monkey/monkey.spec.ts": monkeySpec(),
    "tests/monkey/README.md": harnessReadme(),
    "tests/monkey/security-checklist.md": securityChecklist(),
    ".kit/monkey-test/role-matrix.json": roleMatrixJson(),
    ".kit/monkey-test/expected-findings.example.json": expectedFindingsJson(),
  };
}

async function writeManaged(
  root: string,
  relPath: string,
  content: string,
  force: boolean,
): Promise<HarnessWrite> {
  const path = join(root, relPath);
  const before = await readText(path);
  if (before === content) return { path: relPath, action: "unchanged" };
  if (before && !before.includes(MANAGED) && !force) {
    return {
      path: relPath,
      action: "skipped",
      reason: "exists and is not kit-managed; pass --force to overwrite",
    };
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf-8");
  return { path: relPath, action: before ? "updated" : "created" };
}

export async function writeMonkeyHarness(
  cwd: string = process.cwd(),
  opts: { force?: boolean } = {},
): Promise<HarnessWriteResult> {
  const root = resolve(cwd);
  const writes: HarnessWrite[] = [];
  for (const [relPath, content] of Object.entries(harnessFiles())) {
    writes.push(await writeManaged(root, relPath, content, opts.force === true));
  }
  return { ok: writes.every((w) => w.action !== "skipped"), writes };
}

export function parseEnvOutput(text: string): Record<string, string> {
  const trimmed = text.trim();
  if (!trimmed) return {};
  try {
    const parsed = JSON.parse(trimmed) as Record<string, unknown>;
    return Object.fromEntries(
      Object.entries(parsed)
        .filter(([, value]) => typeof value === "string" || typeof value === "number")
        .map(([key, value]) => [key, String(value)]),
    );
  } catch {
    const out: Record<string, string> = {};
    for (const line of trimmed.split("\n")) {
      const clean = line.trim();
      if (!clean || clean.startsWith("#")) continue;
      const eq = clean.indexOf("=");
      if (eq <= 0) continue;
      const key = clean.slice(0, eq).trim();
      if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
      out[key] = clean.slice(eq + 1).replace(/^["']|["']$/g, "");
    }
    return out;
  }
}

async function runShell(
  command: string,
  opts: { cwd: string; env: NodeJS.ProcessEnv; timeoutMs: number; stream?: boolean },
): Promise<{ ok: boolean; exitCode: number; stdout: string; stderr: string; timedOut: boolean }> {
  return new Promise((resolveRun) => {
    const child = spawn(command, {
      cwd: opts.cwd,
      env: opts.env,
      shell: true,
      stdio: ["ignore", "pipe", "pipe"],
      detached: process.platform !== "win32",
    });
    let stdout = "";
    let stderr = "";
    let timedOut = false;
    const timer = setTimeout(() => {
      timedOut = true;
      killProcess(child);
    }, opts.timeoutMs);
    child.stdout?.on("data", (chunk: Buffer) => {
      stdout += chunk.toString();
      if (opts.stream) process.stdout.write(chunk);
    });
    child.stderr?.on("data", (chunk: Buffer) => {
      stderr += chunk.toString();
      if (opts.stream) process.stderr.write(chunk);
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolveRun({ ok: code === 0 && !timedOut, exitCode: code ?? 1, stdout, stderr, timedOut });
    });
    child.on("error", (error) => {
      clearTimeout(timer);
      resolveRun({ ok: false, exitCode: 127, stdout, stderr: error.message, timedOut });
    });
  });
}

function killProcess(child: ChildProcess): void {
  if (!child.pid) return;
  try {
    if (process.platform === "win32") child.kill("SIGTERM");
    else process.kill(-child.pid, "SIGTERM");
  } catch {
    try {
      child.kill("SIGTERM");
    } catch {
      /* best effort */
    }
  }
}

export async function findFreePort(): Promise<number> {
  return new Promise((resolvePort, reject) => {
    const server = createServer();
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      server.close(() => {
        if (typeof address === "object" && address?.port) resolvePort(address.port);
        else reject(new Error("could not allocate a free port"));
      });
    });
    server.on("error", reject);
  });
}

async function waitForUrl(url: string, timeoutMs: number): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 1000);
    try {
      const response = await fetch(url, { signal: controller.signal });
      clearTimeout(timer);
      if (response.status < 500) return true;
    } catch {
      clearTimeout(timer);
    }
    await new Promise((resolveWait) => setTimeout(resolveWait, 250));
  }
  return false;
}

export async function runMonkeyTest(
  cwd: string = process.cwd(),
  options: MonkeyRunOptions = {},
): Promise<MonkeyRunResult> {
  const root = resolve(cwd);
  const plan = await buildMonkeyTestPlan(root, { envCommand: options.envCommand });
  const findings: MonkeyFinding[] = [];
  const steps: MonkeyRunResult["steps"] = [];
  const expectedReason = options.expectedReason ?? process.env.MONKEY_EXPECTED_REASON;
  const timeoutMs = options.timeoutMs ?? 120_000;
  let server: ChildProcess | null = null;

  if (options.skipSecurity) {
    if (!expectedReason) {
      findings.push(
        finding({
          severity: "critical",
          area: "security",
          title: "--skip-security requires --expected <reason>",
          repro: "kit monkey-test run --skip-security",
          fix: "Run the security pack or record a specific expected reason for this release.",
        }),
      );
    }
    steps.push({ name: "security", status: "skip", detail: expectedReason ?? "missing reason" });
  } else {
    findings.push(...plan.findings);
    steps.push({
      name: "security",
      status: plan.findings.some((f) => ["critical", "high"].includes(f.severity))
        ? "fail"
        : "pass",
      detail: `${plan.findings.length} finding(s)`,
    });
  }

  if (options.skipBrowser) {
    if (!expectedReason) {
      findings.push(
        finding({
          severity: "critical",
          area: "runner",
          title: "--skip-browser requires --expected <reason>",
          repro: "kit monkey-test run --skip-browser",
          fix: "Run the browser crawl or record a specific expected reason for this release.",
        }),
      );
    }
    steps.push({ name: "browser", status: "skip", detail: expectedReason ?? "missing reason" });
    return { ok: findings.length === 0, plan, findings: prioritizeFindings(findings), steps };
  }

  if (!plan.playwright.dependency) {
    findings.push(
      finding({
        severity: "critical",
        area: "runner",
        title: "Playwright dependency missing",
        repro: "kit monkey-test plan",
        file: "package.json",
        fix: "Run `kit triage npm @playwright/test`, install it after a pass, then re-run `kit monkey-test init`.",
      }),
    );
  }
  if (!plan.playwright.monkeyConfig) {
    findings.push(
      finding({
        severity: "critical",
        area: "runner",
        title: "Monkey Playwright config missing",
        repro: "test -f playwright.monkey.config.ts",
        file: "playwright.monkey.config.ts",
        fix: "Run `kit monkey-test init` and commit the generated harness.",
      }),
    );
  }

  const env: NodeJS.ProcessEnv = {
    ...process.env,
    NODE_ENV: process.env.NODE_ENV ?? "test",
    STRIPE_ENV: process.env.STRIPE_ENV ?? "test",
    MONKEY_LINK_DEPTH: String(options.linkDepth ?? process.env.MONKEY_LINK_DEPTH ?? 2),
  };
  if (options.envCommand) {
    const envResult = await runShell(options.envCommand, {
      cwd: root,
      env,
      timeoutMs: 30_000,
    });
    if (envResult.ok) {
      Object.assign(env, parseEnvOutput(envResult.stdout));
      steps.push({ name: "env", status: "pass", detail: "temporary env loaded from command" });
    } else {
      findings.push(
        finding({
          severity: "critical",
          area: "runner",
          title: "Temporary env command failed",
          repro: options.envCommand,
          fix: "Fix the provider CLI/vault export command. Monkey-test never writes these values to .env.",
        }),
      );
      steps.push({ name: "env", status: "fail", detail: envResult.stderr.trim() });
    }
  } else {
    steps.push({ name: "env", status: "skip", detail: "using current process env only" });
  }

  const seedCommand = options.seedCommand ?? plan.commands.seed;
  const skipSeed = options.skipSeed || process.env.SKIP_SEED === "1";
  if (skipSeed) {
    if (!expectedReason) {
      findings.push(
        finding({
          severity: "high",
          area: "runner",
          title: "Seed skipped without expected reason",
          repro: "SKIP_SEED=1 kit monkey-test run",
          fix: "Provide --expected <reason> or run the idempotent seed.",
        }),
      );
    }
    steps.push({ name: "seed", status: "skip", detail: expectedReason ?? "missing reason" });
  } else if (seedCommand) {
    const seed = await runShell(seedCommand, { cwd: root, env, timeoutMs, stream: true });
    if (!seed.ok) {
      findings.push(
        finding({
          severity: "critical",
          area: "runner",
          title: "Seed command failed",
          repro: seedCommand,
          fix: "Make the seed idempotent and runnable in test/sandbox mode.",
        }),
      );
    }
    steps.push({ name: "seed", status: seed.ok ? "pass" : "fail", detail: seedCommand });
  } else {
    findings.push(
      finding({
        severity: "high",
        area: "runner",
        title: "No idempotent seed command detected",
        repro: "kit monkey-test plan",
        file: "package.json",
        fix: "Add a seed script or pass --seed-command. Use --skip-seed only with --expected <reason>.",
      }),
    );
    steps.push({ name: "seed", status: "fail", detail: "missing seed command" });
  }

  const port = options.baseUrl ? undefined : await findFreePort();
  const baseUrl = options.baseUrl ?? `http://127.0.0.1:${port}`;
  env.KIT_MONKEY_PORT = port ? String(port) : env.KIT_MONKEY_PORT;
  env.PORT = port ? String(port) : env.PORT;
  env.MONKEY_BASE_URL = baseUrl;
  const startCommand = options.startCommand ?? plan.commands.dev;
  try {
    if (!options.baseUrl) {
      if (!startCommand) {
        findings.push(
          finding({
            severity: "critical",
            area: "runner",
            title: "No dev server command detected",
            repro: "kit monkey-test run",
            file: "package.json",
            fix: "Add a dev/start script or pass --start-command. The runner needs an isolated local port.",
          }),
        );
      } else {
        server = spawn(startCommand, {
          cwd: root,
          env,
          shell: true,
          stdio: ["ignore", "pipe", "pipe"],
          detached: process.platform !== "win32",
        });
        server.stdout?.on("data", () => undefined);
        server.stderr?.on("data", () => undefined);
        const ready = await waitForUrl(baseUrl, 30_000);
        steps.push({
          name: "dev server",
          status: ready ? "pass" : "fail",
          detail: ready ? `${startCommand} on ${baseUrl}` : `timed out waiting for ${baseUrl}`,
        });
        if (!ready) {
          findings.push(
            finding({
              severity: "critical",
              area: "runner",
              title: "Dev server did not become reachable",
              repro: startCommand,
              fix: "Make the start command honor PORT/KIT_MONKEY_PORT or pass --base-url to an already-running test server.",
            }),
          );
        }
      }
    } else {
      const reachable = await waitForUrl(baseUrl, 5_000);
      steps.push({
        name: "dev server",
        status: reachable ? "pass" : "fail",
        detail: `${baseUrl} ${reachable ? "reachable" : "not reachable"}`,
      });
      if (!reachable) {
        findings.push(
          finding({
            severity: "critical",
            area: "runner",
            title: "Base URL is not reachable",
            repro: baseUrl,
            fix: "Start the app in test mode or let kit start it with --start-command.",
          }),
        );
      }
    }

    if (!findings.some((f) => f.area === "runner" && f.severity === "critical")) {
      const testCommand = options.testCommand ?? plan.commands.test;
      if (!testCommand) {
        findings.push(
          finding({
            severity: "critical",
            area: "runner",
            title: "No Playwright command available",
            repro: "kit monkey-test plan",
            fix: "Install Playwright after triage or pass --test-command.",
          }),
        );
        steps.push({ name: "playwright", status: "fail", detail: "missing command" });
      } else {
        const result = await runShell(testCommand, { cwd: root, env, timeoutMs, stream: true });
        steps.push({
          name: "playwright",
          status: result.ok ? "pass" : "fail",
          detail: result.timedOut ? "timed out" : `exit ${result.exitCode}`,
        });
        if (!result.ok) {
          findings.push(
            finding({
              severity: "critical",
              area: "ux",
              title: "Playwright monkey crawl failed",
              repro: testCommand,
              fix: "Read the Playwright failure and monkey-findings attachment, fix real issues, then re-run.",
            }),
          );
        }
      }
    }
  } finally {
    if (server) killProcess(server);
  }

  const prioritized = prioritizeFindings(findings);
  return { ok: prioritized.length === 0, plan, port, baseUrl, findings: prioritized, steps };
}
