import type { DetectedStack } from "./stack-detector.js";

export type MonkeySeverity = "critical" | "high" | "medium" | "low";
export type MonkeyArea = "runner" | "ux" | "a11y" | "i18n" | "money" | "authz" | "security";

export interface MonkeyRole {
  id: "public" | "customer" | "staff" | "owner" | "superadmin";
  label: string;
  description: string;
  storageStateEnv?: string;
  defaultStorageState?: string;
}

export const MONKEY_ROLES: readonly MonkeyRole[] = [
  {
    id: "public",
    label: "Public visitor",
    description: "Unauthenticated user. Must see only public routes and no private data.",
  },
  {
    id: "customer",
    label: "Customer/buyer",
    description: "Authenticated buyer. Can manage own cart, orders, receipts, and refunds.",
    storageStateEnv: "MONKEY_CUSTOMER_STATE",
    defaultStorageState: ".auth/customer.json",
  },
  {
    id: "staff",
    label: "Kiosk staff",
    description:
      "Frontline kiosk staff role. Keep it separate from owner/admin and from any kiosk device abstraction.",
    storageStateEnv: "MONKEY_STAFF_STATE",
    defaultStorageState: ".auth/staff.json",
  },
  {
    id: "owner",
    label: "Owner/admin",
    description: "Business owner or tenant admin. Can manage catalog, staff, payouts, and reports.",
    storageStateEnv: "MONKEY_OWNER_STATE",
    defaultStorageState: ".auth/owner.json",
  },
  {
    id: "superadmin",
    label: "Superadmin/support",
    description: "Platform support role. Must be audited and isolated from tenant-scoped mutation.",
    storageStateEnv: "MONKEY_SUPERADMIN_STATE",
    defaultStorageState: ".auth/superadmin.json",
  },
];

export interface MonkeyFinding {
  severity: MonkeySeverity;
  area: MonkeyArea;
  title: string;
  role: string;
  route: string;
  repro: string;
  file?: string;
  fix: string;
}

export interface MonkeyExpectedFinding extends Partial<MonkeyFinding> {
  reason?: string;
}

export interface MonkeyRoleExpectation {
  id: MonkeyRole["id"];
  allowRoutes: string[];
  denyRoutes: string[];
  requiredText: string[];
  forbiddenText: string[];
}

export interface MonkeyControlName {
  visibleText?: string;
  buttonValue?: string;
  ariaLabel?: string;
  title?: string;
  associatedLabel?: string;
  labelledByText?: string;
  imageAlt?: string;
}

export interface MonkeyFocusableGeometry {
  left: number;
  right: number;
  top: number;
  bottom: number;
  viewportWidth: number;
  viewportHeight: number;
  display: string;
  visibility: string;
}

export interface MonkeyMoneyFlowConfig {
  mode: "test" | "sandbox";
  action: "cancel" | "confirm";
  route: string;
  addToCart: string;
  checkout: string;
  paymentShell: string;
  sandboxIndicator: string;
  actionControl: string;
  finalState: string;
}

export interface MonkeyPlanCheck {
  name: string;
  status: "pass" | "warn" | "fail" | "skip";
  detail: string;
  file?: string;
}

export interface MonkeyTestPlan {
  cwd: string;
  stack: DetectedStack;
  packageManager: "npm" | "pnpm" | "yarn" | "bun" | "unknown";
  commands: {
    dev?: string;
    build?: string;
    test?: string;
    seed?: string;
  };
  playwright: {
    dependency: boolean;
    config: boolean;
    monkeyConfig: boolean;
  };
  env: {
    kitSecrets: boolean;
    envExample: boolean;
    envCommand?: string;
  };
  money: {
    providers: string[];
    sandboxOnly: boolean;
  };
  harness: {
    files: string[];
    missing: string[];
  };
  roles: readonly MonkeyRole[];
  checks: MonkeyPlanCheck[];
  findings: MonkeyFinding[];
  nextSteps: string[];
}

export interface MonkeyPlanOptions {
  envCommand?: string;
}

export interface HarnessWrite {
  path: string;
  action: "created" | "updated" | "unchanged" | "skipped";
  reason?: string;
}

export interface HarnessWriteResult {
  ok: boolean;
  writes: HarnessWrite[];
}

export interface MonkeyRunOptions {
  baseUrl?: string;
  startCommand?: string;
  seedCommand?: string;
  testCommand?: string;
  envCommand?: string;
  linkDepth?: number;
  skipSeed?: boolean;
  skipBrowser?: boolean;
  skipSecurity?: boolean;
  expectedReason?: string;
  timeoutMs?: number;
}

export interface MonkeyRunResult {
  ok: boolean;
  plan: MonkeyTestPlan;
  port?: number;
  baseUrl?: string;
  findings: MonkeyFinding[];
  steps: { name: string; status: "pass" | "fail" | "skip"; detail: string }[];
}

export interface MonkeyPackageJson {
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  packageManager?: string;
  prisma?: { seed?: string };
}

export const MONKEY_MANAGED = "Generated by kit monkey-test";
export const MONKEY_PLAYWRIGHT_REPORT = ".kit/monkey-test/playwright-report.json";
export const MONKEY_HARNESS_FILES = [
  "playwright.monkey.config.ts",
  "tests/monkey/monkey.spec.ts",
  "tests/monkey/README.md",
  "tests/monkey/security-checklist.md",
  ".kit/monkey-test/role-matrix.json",
  ".kit/monkey-test/expected-findings.example.json",
] as const;

export function monkeyFinding(
  input: Omit<MonkeyFinding, "role" | "route"> & Partial<Pick<MonkeyFinding, "role" | "route">>,
): MonkeyFinding {
  return {
    ...input,
    role: input.role ?? "all",
    route: input.route ?? "*",
  };
}

export function prioritizeFindings(findings: MonkeyFinding[]): MonkeyFinding[] {
  const weight: Record<MonkeySeverity, number> = { critical: 0, high: 1, medium: 2, low: 3 };
  return [...findings].sort(
    (a, b) =>
      weight[a.severity] - weight[b.severity] ||
      a.area.localeCompare(b.area) ||
      a.title.localeCompare(b.title),
  );
}

export function validateExpectedFindings(value: unknown): MonkeyExpectedFinding[] {
  if (!Array.isArray(value)) throw new Error("MONKEY_EXPECTED_FINDINGS must contain a JSON array.");
  for (const item of value) {
    if (!item || typeof item !== "object") {
      throw new Error("MONKEY_EXPECTED_FINDINGS entries must be JSON objects.");
    }
    const expected = item as MonkeyExpectedFinding;
    if (!expected.reason || expected.reason.trim().length < 8) {
      throw new Error("MONKEY_EXPECTED_FINDINGS entries must include a specific reason.");
    }
    if (!expected.title?.trim() || !expected.role?.trim() || !expected.route?.trim()) {
      throw new Error(
        "MONKEY_EXPECTED_FINDINGS entries must identify exact title, role, and route.",
      );
    }
  }
  return value as MonkeyExpectedFinding[];
}

export function matchesExpectedFinding(
  actual: MonkeyFinding,
  expected: MonkeyExpectedFinding,
): boolean {
  const keys = ["severity", "area", "title", "role", "route", "repro", "file"] as const;
  return keys.every((key) => expected[key] === undefined || expected[key] === actual[key]);
}

export function unexpectedMonkeyFindings(
  findings: MonkeyFinding[],
  expectedValue: unknown,
): MonkeyFinding[] {
  const expected = validateExpectedFindings(expectedValue);
  return findings.filter(
    (actual) => !expected.some((candidate) => matchesExpectedFinding(actual, candidate)),
  );
}

// The role-matrix chain below is embedded verbatim into the generated Playwright
// spec by monkey-test-harness-spec.ts, which is why every part of it is exported:
// a helper left behind resolves to nothing in the generated file and throws
// ReferenceError on load. monkey-test-harness-spec.test.ts evaluates the
// generated spec and fails if a piece is missing.
export const MONKEY_ROLE_IDS = ["public", "customer", "staff", "owner", "superadmin"] as const;
export const MONKEY_ROLE_LIST_KEYS = [
  "allowRoutes",
  "denyRoutes",
  "requiredText",
  "forbiddenText",
] as const;
export const MONKEY_ROLE_ROUTE_KEYS = ["allowRoutes", "denyRoutes"] as const;

type MonkeyRoleListKey = (typeof MONKEY_ROLE_LIST_KEYS)[number];

export function configuredRoleEntries(value: unknown): unknown[] {
  const matrix = value as { configured?: unknown; roles?: unknown } | null;
  if (!matrix || typeof matrix !== "object" || matrix.configured !== true) {
    throw new Error("Monkey role matrix must be reviewed and set to configured: true.");
  }
  if (!Array.isArray(matrix.roles)) throw new Error("Monkey role matrix must contain roles.");
  if (matrix.roles.length !== MONKEY_ROLE_IDS.length) {
    throw new Error("Monkey role matrix must contain each required role exactly once.");
  }
  return matrix.roles;
}

export function isRoleWithId(
  candidate: unknown,
  id: MonkeyRole["id"],
): candidate is Record<string, unknown> {
  return Boolean(
    candidate && typeof candidate === "object" && (candidate as { id?: unknown }).id === id,
  );
}

export function requiredRole(entries: unknown[], id: MonkeyRole["id"]): Record<string, unknown> {
  const matching = entries.filter((candidate) => isRoleWithId(candidate, id));
  if (matching.length !== 1) throw new Error(`Monkey role matrix requires exactly one ${id}.`);
  return matching[0];
}

export function requiredStringList(
  role: Record<string, unknown>,
  id: MonkeyRole["id"],
  key: MonkeyRoleListKey,
): string[] {
  const entries = role[key];
  if (
    !Array.isArray(entries) ||
    entries.length === 0 ||
    entries.some((entry) => typeof entry !== "string" || entry.trim().length === 0)
  ) {
    throw new Error(`Monkey role ${id} requires non-empty ${key}.`);
  }
  if (entries.some((entry) => /replace-with-/i.test(entry))) {
    throw new Error(`Monkey role ${id} still contains a generated placeholder in ${key}.`);
  }
  return entries;
}

export function requireSameOriginRoutes(
  routes: string[],
  id: MonkeyRole["id"],
  key: (typeof MONKEY_ROLE_ROUTE_KEYS)[number],
): void {
  if (routes.some((route) => !route.startsWith("/") || route.startsWith("//"))) {
    throw new Error(`Monkey role ${id} ${key} must contain same-origin route paths.`);
  }
}

export function requireDisjointValues(included: string[], excluded: string[], message: string): void {
  const includedValues = new Set(included);
  if (excluded.some((value) => includedValues.has(value))) throw new Error(message);
}

export function validateRoleExpectation(role: Record<string, unknown>, id: MonkeyRole["id"]): void {
  const lists = Object.fromEntries(
    MONKEY_ROLE_LIST_KEYS.map((key) => [key, requiredStringList(role, id, key)]),
  ) as Record<MonkeyRoleListKey, string[]>;
  for (const key of MONKEY_ROLE_ROUTE_KEYS) requireSameOriginRoutes(lists[key], id, key);
  requireDisjointValues(
    lists.allowRoutes,
    lists.denyRoutes,
    `Monkey role ${id} cannot allow and deny the same route.`,
  );
  requireDisjointValues(
    lists.requiredText,
    lists.forbiddenText,
    `Monkey role ${id} cannot require and forbid the same marker.`,
  );
}

export function validateRoleMatrix(value: unknown): MonkeyRoleExpectation[] {
  const entries = configuredRoleEntries(value);
  for (const id of MONKEY_ROLE_IDS) {
    validateRoleExpectation(requiredRole(entries, id), id);
  }
  return entries as MonkeyRoleExpectation[];
}

export function controlHasAccessibleName(control: MonkeyControlName): boolean {
  return [
    control.visibleText,
    control.buttonValue,
    control.ariaLabel,
    control.title,
    control.associatedLabel,
    control.labelledByText,
    control.imageAlt,
  ].some((value) => typeof value === "string" && value.trim().length > 0);
}

export function focusableIsOffscreen(geometry: MonkeyFocusableGeometry): boolean {
  if (geometry.display === "none" || geometry.visibility === "hidden") return false;
  if (
    geometry.viewportWidth <= 0 ||
    geometry.viewportHeight <= 0 ||
    geometry.right <= geometry.left ||
    geometry.bottom <= geometry.top
  ) {
    return false;
  }
  return geometry.right <= 0 || geometry.left >= geometry.viewportWidth || geometry.bottom <= 0;
}

export function validateMoneyFlowConfig(
  env: Record<string, string | undefined>,
): MonkeyMoneyFlowConfig {
  const mode = env.MONKEY_PAYMENT_MODE?.toLowerCase();
  if (mode !== "test" && mode !== "sandbox") {
    throw new Error("MONKEY_PAYMENT_MODE must be test or sandbox.");
  }
  const requestedAction =
    env.MONKEY_PAYMENT_ACTION ?? (env.MONKEY_CONFIRM_TEST_PAYMENT === "1" ? "confirm" : "cancel");
  if (requestedAction !== "cancel" && requestedAction !== "confirm") {
    throw new Error("MONKEY_PAYMENT_ACTION must be cancel or confirm.");
  }
  const actionControlName =
    requestedAction === "confirm" ? "MONKEY_CONFIRM_PAYMENT" : "MONKEY_CANCEL_PAYMENT";
  const finalStateName =
    requestedAction === "confirm" ? "MONKEY_CONFIRMED_STATE" : "MONKEY_CANCELLED_STATE";
  const required = [
    ["MONKEY_MONEY_ROUTE", env.MONKEY_MONEY_ROUTE],
    ["MONKEY_ADD_TO_CART", env.MONKEY_ADD_TO_CART],
    ["MONKEY_CHECKOUT", env.MONKEY_CHECKOUT],
    ["MONKEY_PAYMENT_SHELL", env.MONKEY_PAYMENT_SHELL],
    ["MONKEY_SANDBOX_INDICATOR", env.MONKEY_SANDBOX_INDICATOR],
    [actionControlName, env[actionControlName]],
    [finalStateName, env[finalStateName]],
  ];
  const missing = required.filter(([, value]) => !value?.trim()).map(([name]) => name);
  if (missing.length > 0) throw new Error(`Money flow requires ${missing.join(", ")}.`);
  return {
    mode,
    action: requestedAction,
    route: env.MONKEY_MONEY_ROUTE!,
    addToCart: env.MONKEY_ADD_TO_CART!,
    checkout: env.MONKEY_CHECKOUT!,
    paymentShell: env.MONKEY_PAYMENT_SHELL!,
    sandboxIndicator: env.MONKEY_SANDBOX_INDICATOR!,
    actionControl: env[actionControlName]!,
    finalState: env[finalStateName]!,
  };
}
