/** Generated OpenCode install gate plugin. */
export function renderOpenCodeInstallGate(): string {
  return `// kit install-gate — blocks un-triaged package installs before they run.
// Generated by \`kit agent-config --install-gate\`. Delete this file to disable.
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

function gateArgv() {
  const wrapper = join(homedir(), ".kit", "bin", process.platform === "win32" ? "kit.cmd" : "kit");
  if (!existsSync(wrapper)) {
    throw new Error(
      "kit install-gate cannot start: hook wrapper missing: " + wrapper + "; run kit agent-config",
    );
  }
  return [wrapper, "gate-bash"];
}

export const kitInstallGate = async () => ({
  "tool.execute.before": async (input, output) => {
    if ((input?.tool ?? "") !== "bash") return;
    const command = output?.args?.command;
    if (typeof command !== "string" || command === "") return;
    try {
      const gate = gateArgv();
      // Windows cannot execFile a .cmd file directly. Only the fixed, local
      // wrapper path enters cmd.exe; the pending tool command stays on stdin.
      const executable = process.platform === "win32" ? (process.env.ComSpec || "cmd.exe") : gate[0];
      const args = process.platform === "win32"
        ? ["/d", "/s", "/c", '"' + '"' + gate[0] + '" gate-bash' + '"']
        : gate.slice(1);
      execFileSync(executable, args, {
        input: JSON.stringify({ tool_input: { command } }),
        stdio: ["pipe", "ignore", "pipe"],
        windowsVerbatimArguments: process.platform === "win32",
      });
    } catch (err) {
      // gate-bash exits 2 to deny — throw to block the tool call.
      const reason = err && err.stderr ? String(err.stderr).trim() : "untriaged install";
      throw new Error("kit install-gate blocked: " + reason, { cause: err });
    }
  },
});
`;
}
