import { readFile, writeFile, access } from "node:fs/promises";
import type { SecretsConfig } from "./config.js";
import { resolveViaBackend, resetInfisicalCache } from "./secret-backends.js";


export interface SecretResolveResult {
  name: string;
  resolved: boolean;
  value: string | null;
  detail: string;
  /** True when the backend manages the value out-of-band (e.g. EAS) — `value`
   *  is a display placeholder, not a real secret, so it's never written to
   *  .env.local. Lets the writer skip these without sniffing the value string. */
  managed?: boolean;
}

/** Interpolate {{KEY}} placeholders in a template string with resolved values. */
function interpolateTemplate(
  template: string,
  resolved: Map<string, string>,
): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_match, key: string) => {
    return resolved.get(key) ?? `{{${key}}}`;
  });
}

async function loadTemplate(templatePath: string): Promise<string | null> {
  try {
    await access(templatePath);
    return await readFile(templatePath, "utf-8");
  } catch {
    return null;
  }
}

export async function generateSecrets(
  secrets: SecretsConfig,
  outputPath: string = ".env.local",
): Promise<{
  results: SecretResolveResult[];
  written: boolean;
  fromTemplate: boolean;
  skipped?: "nothing-resolved";
}> {
  const results: SecretResolveResult[] = [];

  if (!secrets.keys) {
    return { results, written: false, fromTemplate: false };
  }

  // Reset the Infisical bulk-fetch cache for each generateSecrets call.
  resetInfisicalCache();

  for (const [name, config] of Object.entries(secrets.keys)) {
    results.push(await resolveViaBackend(name, config, secrets.infisical));
  }

  // Build a lookup of resolved values
  const resolved = new Map<string, string>();
  for (const r of results) {
    // Skip backend-managed values (e.g. EAS) — their `value` is a display
    // placeholder, not a real secret to write into .env.local.
    if (r.resolved && r.value !== null && !r.managed) {
      resolved.set(r.name, r.value);
    }
  }

  let content: string;
  let fromTemplate = false;

  // If a template is configured, read it and interpolate
  const template = secrets.template ? await loadTemplate(secrets.template) : null;

  if (template !== null) {
    fromTemplate = true;
    const header = [
      "# Generated by kit secrets from template — do not edit manually",
      `# Template: ${secrets.template}`,
      `# Generated at ${new Date().toISOString()}`,
      "",
    ].join("\n");
    content = header + interpolateTemplate(template, resolved) + "\n";
  } else {
    // Fallback: generate from keys
    const lines: string[] = [
      "# Generated by kit secrets — do not edit manually",
      `# Generated at ${new Date().toISOString()}`,
      "",
    ];

    for (const result of results) {
      if (resolved.has(result.name)) {
        lines.push(`${result.name}=${resolved.get(result.name)}`);
      } else {
        lines.push(`# ${result.name}= # ${result.detail}`);
      }
    }

    lines.push("");
    content = lines.join("\n");
  }

  // Never clobber an existing .env.local when we resolved nothing. The source
  // (vault) being empty/unauthed is not a reason to replace a working file
  // with an empty scaffold — that destroys local-dev credentials. Leave it
  // untouched and report the skip so the caller can say so.
  if (resolved.size === 0) {
    const fileExists = await access(outputPath).then(
      () => true,
      () => false,
    );
    if (fileExists) {
      return { results, written: false, fromTemplate, skipped: "nothing-resolved" };
    }
  }

  await writeFile(outputPath, content, "utf-8");
  return { results, written: true, fromTemplate };
}
